package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum BA {
   SPAWN_ENTITY,
   SPAWN_EXPERIENCE_ORB,
   SPAWN_WEATHER_ENTITY,
   SPAWN_LIVING_ENTITY,
   SPAWN_PAINTING,
   SPAWN_PLAYER,
   ENTITY_ANIMATION,
   STATISTICS,
   BLOCK_BREAK_ANIMATION,
   BLOCK_ENTITY_DATA,
   BLOCK_ACTION,
   BLOCK_CHANGE,
   BOSS_BAR,
   SERVER_DIFFICULTY,
   CHAT_MESSAGE,
   MULTI_BLOCK_CHANGE,
   TAB_COMPLETE,
   DECLARE_COMMANDS,
   WINDOW_CONFIRMATION,
   CLOSE_WINDOW,
   WINDOW_ITEMS,
   WINDOW_PROPERTY,
   SET_SLOT,
   SET_COOLDOWN,
   PLUGIN_MESSAGE,
   NAMED_SOUND_EFFECT,
   DISCONNECT,
   ENTITY_STATUS,
   EXPLOSION,
   UNLOAD_CHUNK,
   CHANGE_GAME_STATE,
   OPEN_HORSE_WINDOW,
   KEEP_ALIVE,
   CHUNK_DATA,
   EFFECT,
   PARTICLE,
   UPDATE_LIGHT,
   JOIN_GAME,
   MAP_DATA,
   MERCHANT_OFFERS,
   ENTITY_RELATIVE_MOVE,
   ENTITY_RELATIVE_MOVE_AND_ROTATION,
   ENTITY_ROTATION,
   ENTITY_MOVEMENT,
   VEHICLE_MOVE,
   OPEN_BOOK,
   OPEN_WINDOW,
   OPEN_SIGN_EDITOR,
   CRAFT_RECIPE_RESPONSE,
   PLAYER_ABILITIES,
   COMBAT_EVENT,
   PLAYER_INFO,
   FACE_PLAYER,
   PLAYER_POSITION_AND_LOOK,
   UNLOCK_RECIPES,
   DESTROY_ENTITIES,
   REMOVE_ENTITY_EFFECT,
   RESOURCE_PACK_SEND,
   RESPAWN,
   ENTITY_HEAD_LOOK,
   SELECT_ADVANCEMENTS_TAB,
   WORLD_BORDER,
   CAMERA,
   HELD_ITEM_CHANGE,
   UPDATE_VIEW_POSITION,
   UPDATE_VIEW_DISTANCE,
   DISPLAY_SCOREBOARD,
   ENTITY_METADATA,
   ATTACH_ENTITY,
   ENTITY_VELOCITY,
   ENTITY_EQUIPMENT,
   SET_EXPERIENCE,
   UPDATE_HEALTH,
   SCOREBOARD_OBJECTIVE,
   SET_PASSENGERS,
   TEAMS,
   UPDATE_SCORE,
   SPAWN_POSITION,
   TIME_UPDATE,
   TITLE,
   ENTITY_SOUND_EFFECT,
   SOUND_EFFECT,
   STOP_SOUND,
   PLAYER_LIST_HEADER_AND_FOOTER,
   NBT_QUERY_RESPONSE,
   COLLECT_ITEM,
   ENTITY_TELEPORT,
   UPDATE_ADVANCEMENTS,
   UPDATE_ATTRIBUTES,
   ENTITY_EFFECT,
   DECLARE_RECIPES,
   TAGS;

   // $FF: synthetic method
   private static BA[] z() {
      return new BA[]{SPAWN_ENTITY, SPAWN_EXPERIENCE_ORB, SPAWN_WEATHER_ENTITY, SPAWN_LIVING_ENTITY, SPAWN_PAINTING, SPAWN_PLAYER, ENTITY_ANIMATION, STATISTICS, BLOCK_BREAK_ANIMATION, BLOCK_ENTITY_DATA, BLOCK_ACTION, BLOCK_CHANGE, BOSS_BAR, SERVER_DIFFICULTY, CHAT_MESSAGE, MULTI_BLOCK_CHANGE, TAB_COMPLETE, DECLARE_COMMANDS, WINDOW_CONFIRMATION, CLOSE_WINDOW, WINDOW_ITEMS, WINDOW_PROPERTY, SET_SLOT, SET_COOLDOWN, PLUGIN_MESSAGE, NAMED_SOUND_EFFECT, DISCONNECT, ENTITY_STATUS, EXPLOSION, UNLOAD_CHUNK, CHANGE_GAME_STATE, OPEN_HORSE_WINDOW, KEEP_ALIVE, CHUNK_DATA, EFFECT, PARTICLE, UPDATE_LIGHT, JOIN_GAME, MAP_DATA, MERCHANT_OFFERS, ENTITY_RELATIVE_MOVE, ENTITY_RELATIVE_MOVE_AND_ROTATION, ENTITY_ROTATION, ENTITY_MOVEMENT, VEHICLE_MOVE, OPEN_BOOK, OPEN_WINDOW, OPEN_SIGN_EDITOR, CRAFT_RECIPE_RESPONSE, PLAYER_ABILITIES, COMBAT_EVENT, PLAYER_INFO, FACE_PLAYER, PLAYER_POSITION_AND_LOOK, UNLOCK_RECIPES, DESTROY_ENTITIES, REMOVE_ENTITY_EFFECT, RESOURCE_PACK_SEND, RESPAWN, ENTITY_HEAD_LOOK, SELECT_ADVANCEMENTS_TAB, WORLD_BORDER, CAMERA, HELD_ITEM_CHANGE, UPDATE_VIEW_POSITION, UPDATE_VIEW_DISTANCE, DISPLAY_SCOREBOARD, ENTITY_METADATA, ATTACH_ENTITY, ENTITY_VELOCITY, ENTITY_EQUIPMENT, SET_EXPERIENCE, UPDATE_HEALTH, SCOREBOARD_OBJECTIVE, SET_PASSENGERS, TEAMS, UPDATE_SCORE, SPAWN_POSITION, TIME_UPDATE, TITLE, ENTITY_SOUND_EFFECT, SOUND_EFFECT, STOP_SOUND, PLAYER_LIST_HEADER_AND_FOOTER, NBT_QUERY_RESPONSE, COLLECT_ITEM, ENTITY_TELEPORT, UPDATE_ADVANCEMENTS, UPDATE_ATTRIBUTES, ENTITY_EFFECT, DECLARE_RECIPES, TAGS};
   }

   static {
      long var0 = kt.a(3478199639288888865L, 633218751003164296L, MethodHandles.lookup().lookupClass()).a(232660763277599L) ^ 121880258623880L;
      SPAWN_ENTITY = new BA("SPAWN_ENTITY", 0);
      SPAWN_EXPERIENCE_ORB = new BA("SPAWN_EXPERIENCE_ORB", 1);
      SPAWN_WEATHER_ENTITY = new BA("SPAWN_WEATHER_ENTITY", 2);
      SPAWN_LIVING_ENTITY = new BA("SPAWN_LIVING_ENTITY", 3);
      SPAWN_PAINTING = new BA("SPAWN_PAINTING", 4);
      SPAWN_PLAYER = new BA("SPAWN_PLAYER", 5);
      ENTITY_ANIMATION = new BA("ENTITY_ANIMATION", 6);
      STATISTICS = new BA("STATISTICS", 7);
      BLOCK_BREAK_ANIMATION = new BA("BLOCK_BREAK_ANIMATION", 8);
      BLOCK_ENTITY_DATA = new BA("BLOCK_ENTITY_DATA", 9);
      BLOCK_ACTION = new BA("BLOCK_ACTION", 10);
      BLOCK_CHANGE = new BA("BLOCK_CHANGE", 11);
      BOSS_BAR = new BA("BOSS_BAR", 12);
      SERVER_DIFFICULTY = new BA("SERVER_DIFFICULTY", 13);
      CHAT_MESSAGE = new BA("CHAT_MESSAGE", 14);
      MULTI_BLOCK_CHANGE = new BA("MULTI_BLOCK_CHANGE", 15);
      TAB_COMPLETE = new BA("TAB_COMPLETE", 16);
      DECLARE_COMMANDS = new BA("DECLARE_COMMANDS", 17);
      WINDOW_CONFIRMATION = new BA("WINDOW_CONFIRMATION", 18);
      CLOSE_WINDOW = new BA("CLOSE_WINDOW", 19);
      WINDOW_ITEMS = new BA("WINDOW_ITEMS", 20);
      WINDOW_PROPERTY = new BA("WINDOW_PROPERTY", 21);
      SET_SLOT = new BA("SET_SLOT", 22);
      SET_COOLDOWN = new BA("SET_COOLDOWN", 23);
      PLUGIN_MESSAGE = new BA("PLUGIN_MESSAGE", 24);
      NAMED_SOUND_EFFECT = new BA("NAMED_SOUND_EFFECT", 25);
      DISCONNECT = new BA("DISCONNECT", 26);
      ENTITY_STATUS = new BA("ENTITY_STATUS", 27);
      EXPLOSION = new BA("EXPLOSION", 28);
      UNLOAD_CHUNK = new BA("UNLOAD_CHUNK", 29);
      CHANGE_GAME_STATE = new BA("CHANGE_GAME_STATE", 30);
      OPEN_HORSE_WINDOW = new BA("OPEN_HORSE_WINDOW", 31);
      KEEP_ALIVE = new BA("KEEP_ALIVE", 32);
      CHUNK_DATA = new BA("CHUNK_DATA", 33);
      EFFECT = new BA("EFFECT", 34);
      PARTICLE = new BA("PARTICLE", 35);
      UPDATE_LIGHT = new BA("UPDATE_LIGHT", 36);
      JOIN_GAME = new BA("JOIN_GAME", 37);
      MAP_DATA = new BA("MAP_DATA", 38);
      MERCHANT_OFFERS = new BA("MERCHANT_OFFERS", 39);
      ENTITY_RELATIVE_MOVE = new BA("ENTITY_RELATIVE_MOVE", 40);
      ENTITY_RELATIVE_MOVE_AND_ROTATION = new BA("ENTITY_RELATIVE_MOVE_AND_ROTATION", 41);
      ENTITY_ROTATION = new BA("ENTITY_ROTATION", 42);
      ENTITY_MOVEMENT = new BA("ENTITY_MOVEMENT", 43);
      VEHICLE_MOVE = new BA("VEHICLE_MOVE", 44);
      OPEN_BOOK = new BA("OPEN_BOOK", 45);
      OPEN_WINDOW = new BA("OPEN_WINDOW", 46);
      OPEN_SIGN_EDITOR = new BA("OPEN_SIGN_EDITOR", 47);
      CRAFT_RECIPE_RESPONSE = new BA("CRAFT_RECIPE_RESPONSE", 48);
      PLAYER_ABILITIES = new BA("PLAYER_ABILITIES", 49);
      COMBAT_EVENT = new BA("COMBAT_EVENT", 50);
      PLAYER_INFO = new BA("PLAYER_INFO", 51);
      FACE_PLAYER = new BA("FACE_PLAYER", 52);
      PLAYER_POSITION_AND_LOOK = new BA("PLAYER_POSITION_AND_LOOK", 53);
      UNLOCK_RECIPES = new BA("UNLOCK_RECIPES", 54);
      DESTROY_ENTITIES = new BA("DESTROY_ENTITIES", 55);
      REMOVE_ENTITY_EFFECT = new BA("REMOVE_ENTITY_EFFECT", 56);
      RESOURCE_PACK_SEND = new BA("RESOURCE_PACK_SEND", 57);
      RESPAWN = new BA("RESPAWN", 58);
      ENTITY_HEAD_LOOK = new BA("ENTITY_HEAD_LOOK", 59);
      SELECT_ADVANCEMENTS_TAB = new BA("SELECT_ADVANCEMENTS_TAB", 60);
      WORLD_BORDER = new BA("WORLD_BORDER", 61);
      CAMERA = new BA("CAMERA", 62);
      HELD_ITEM_CHANGE = new BA("HELD_ITEM_CHANGE", 63);
      UPDATE_VIEW_POSITION = new BA("UPDATE_VIEW_POSITION", 64);
      UPDATE_VIEW_DISTANCE = new BA("UPDATE_VIEW_DISTANCE", 65);
      DISPLAY_SCOREBOARD = new BA("DISPLAY_SCOREBOARD", 66);
      ENTITY_METADATA = new BA("ENTITY_METADATA", 67);
      ATTACH_ENTITY = new BA("ATTACH_ENTITY", 68);
      ENTITY_VELOCITY = new BA("ENTITY_VELOCITY", 69);
      ENTITY_EQUIPMENT = new BA("ENTITY_EQUIPMENT", 70);
      SET_EXPERIENCE = new BA("SET_EXPERIENCE", 71);
      UPDATE_HEALTH = new BA("UPDATE_HEALTH", 72);
      SCOREBOARD_OBJECTIVE = new BA("SCOREBOARD_OBJECTIVE", 73);
      SET_PASSENGERS = new BA("SET_PASSENGERS", 74);
      TEAMS = new BA("TEAMS", 75);
      UPDATE_SCORE = new BA("UPDATE_SCORE", 76);
      SPAWN_POSITION = new BA("SPAWN_POSITION", 77);
      TIME_UPDATE = new BA("TIME_UPDATE", 78);
      TITLE = new BA("TITLE", 79);
      ENTITY_SOUND_EFFECT = new BA("ENTITY_SOUND_EFFECT", 80);
      SOUND_EFFECT = new BA("SOUND_EFFECT", 81);
      STOP_SOUND = new BA("STOP_SOUND", 82);
      PLAYER_LIST_HEADER_AND_FOOTER = new BA("PLAYER_LIST_HEADER_AND_FOOTER", 83);
      NBT_QUERY_RESPONSE = new BA("NBT_QUERY_RESPONSE", 84);
      COLLECT_ITEM = new BA("COLLECT_ITEM", 85);
      ENTITY_TELEPORT = new BA("ENTITY_TELEPORT", 86);
      UPDATE_ADVANCEMENTS = new BA("UPDATE_ADVANCEMENTS", 87);
      UPDATE_ATTRIBUTES = new BA("UPDATE_ATTRIBUTES", 88);
      ENTITY_EFFECT = new BA("ENTITY_EFFECT", 89);
      DECLARE_RECIPES = new BA("DECLARE_RECIPES", 90);
      TAGS = new BA("TAGS", 91);
   }
}
