package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum c5 {
   BUNDLE,
   SPAWN_ENTITY,
   SPAWN_EXPERIENCE_ORB,
   ENTITY_ANIMATION,
   STATISTICS,
   ACKNOWLEDGE_BLOCK_CHANGES,
   BLOCK_BREAK_ANIMATION,
   BLOCK_ENTITY_DATA,
   BLOCK_ACTION,
   BLOCK_CHANGE,
   BOSS_BAR,
   SERVER_DIFFICULTY,
   CHUNK_BATCH_END,
   CHUNK_BATCH_BEGIN,
   CHUNK_BIOMES,
   CLEAR_TITLES,
   TAB_COMPLETE,
   DECLARE_COMMANDS,
   CLOSE_WINDOW,
   WINDOW_ITEMS,
   WINDOW_PROPERTY,
   SET_SLOT,
   SET_COOLDOWN,
   CUSTOM_CHAT_COMPLETIONS,
   PLUGIN_MESSAGE,
   DAMAGE_EVENT,
   DELETE_CHAT,
   DISCONNECT,
   DISGUISED_CHAT,
   ENTITY_STATUS,
   EXPLOSION,
   UNLOAD_CHUNK,
   CHANGE_GAME_STATE,
   OPEN_HORSE_WINDOW,
   HURT_ANIMATION,
   INITIALIZE_WORLD_BORDER,
   KEEP_ALIVE,
   CHUNK_DATA,
   EFFECT,
   PARTICLE,
   UPDATE_LIGHT,
   JOIN_GAME,
   MAP_DATA,
   MERCHANT_OFFERS,
   ENTITY_RELATIVE_MOVE,
   ENTITY_RELATIVE_MOVE_AND_ROTATION,
   ENTITY_ROTATION,
   VEHICLE_MOVE,
   OPEN_BOOK,
   OPEN_WINDOW,
   OPEN_SIGN_EDITOR,
   PING,
   DEBUG_PONG,
   CRAFT_RECIPE_RESPONSE,
   PLAYER_ABILITIES,
   CHAT_MESSAGE,
   END_COMBAT_EVENT,
   ENTER_COMBAT_EVENT,
   DEATH_COMBAT_EVENT,
   PLAYER_INFO_REMOVE,
   PLAYER_INFO_UPDATE,
   FACE_PLAYER,
   PLAYER_POSITION_AND_LOOK,
   UNLOCK_RECIPES,
   DESTROY_ENTITIES,
   REMOVE_ENTITY_EFFECT,
   RESET_SCORE,
   RESOURCE_PACK_REMOVE,
   RESOURCE_PACK_SEND,
   RESPAWN,
   ENTITY_HEAD_LOOK,
   MULTI_BLOCK_CHANGE,
   SELECT_ADVANCEMENTS_TAB,
   SERVER_DATA,
   ACTION_BAR,
   WORLD_BORDER_CENTER,
   WORLD_BORDER_LERP_SIZE,
   WORLD_BORDER_SIZE,
   WORLD_BORDER_WARNING_DELAY,
   WORLD_BORDER_WARNING_REACH,
   CAMERA,
   HELD_ITEM_CHANGE,
   UPDATE_VIEW_POSITION,
   UPDATE_VIEW_DISTANCE,
   SPAWN_POSITION,
   DISPLAY_SCOREBOARD,
   ENTITY_METADATA,
   ATTACH_ENTITY,
   ENTITY_VELOCITY,
   ENTITY_EQUIPMENT,
   SET_EXPERIENCE,
   UPDATE_HEALTH,
   SCOREBOARD_OBJECTIVE,
   SET_PASSENGERS,
   TEAMS,
   UPDATE_SCORE,
   UPDATE_SIMULATION_DISTANCE,
   SET_TITLE_SUBTITLE,
   TIME_UPDATE,
   SET_TITLE_TEXT,
   SET_TITLE_TIMES,
   ENTITY_SOUND_EFFECT,
   SOUND_EFFECT,
   CONFIGURATION_START,
   STOP_SOUND,
   SYSTEM_CHAT_MESSAGE,
   PLAYER_LIST_HEADER_AND_FOOTER,
   NBT_QUERY_RESPONSE,
   COLLECT_ITEM,
   ENTITY_TELEPORT,
   TICKING_STATE,
   TICKING_STEP,
   UPDATE_ADVANCEMENTS,
   UPDATE_ATTRIBUTES,
   ENTITY_EFFECT,
   DECLARE_RECIPES,
   TAGS;

   // $FF: synthetic method
   private static c5[] C() {
      return new c5[]{BUNDLE, SPAWN_ENTITY, SPAWN_EXPERIENCE_ORB, ENTITY_ANIMATION, STATISTICS, ACKNOWLEDGE_BLOCK_CHANGES, BLOCK_BREAK_ANIMATION, BLOCK_ENTITY_DATA, BLOCK_ACTION, BLOCK_CHANGE, BOSS_BAR, SERVER_DIFFICULTY, CHUNK_BATCH_END, CHUNK_BATCH_BEGIN, CHUNK_BIOMES, CLEAR_TITLES, TAB_COMPLETE, DECLARE_COMMANDS, CLOSE_WINDOW, WINDOW_ITEMS, WINDOW_PROPERTY, SET_SLOT, SET_COOLDOWN, CUSTOM_CHAT_COMPLETIONS, PLUGIN_MESSAGE, DAMAGE_EVENT, DELETE_CHAT, DISCONNECT, DISGUISED_CHAT, ENTITY_STATUS, EXPLOSION, UNLOAD_CHUNK, CHANGE_GAME_STATE, OPEN_HORSE_WINDOW, HURT_ANIMATION, INITIALIZE_WORLD_BORDER, KEEP_ALIVE, CHUNK_DATA, EFFECT, PARTICLE, UPDATE_LIGHT, JOIN_GAME, MAP_DATA, MERCHANT_OFFERS, ENTITY_RELATIVE_MOVE, ENTITY_RELATIVE_MOVE_AND_ROTATION, ENTITY_ROTATION, VEHICLE_MOVE, OPEN_BOOK, OPEN_WINDOW, OPEN_SIGN_EDITOR, PING, DEBUG_PONG, CRAFT_RECIPE_RESPONSE, PLAYER_ABILITIES, CHAT_MESSAGE, END_COMBAT_EVENT, ENTER_COMBAT_EVENT, DEATH_COMBAT_EVENT, PLAYER_INFO_REMOVE, PLAYER_INFO_UPDATE, FACE_PLAYER, PLAYER_POSITION_AND_LOOK, UNLOCK_RECIPES, DESTROY_ENTITIES, REMOVE_ENTITY_EFFECT, RESET_SCORE, RESOURCE_PACK_REMOVE, RESOURCE_PACK_SEND, RESPAWN, ENTITY_HEAD_LOOK, MULTI_BLOCK_CHANGE, SELECT_ADVANCEMENTS_TAB, SERVER_DATA, ACTION_BAR, WORLD_BORDER_CENTER, WORLD_BORDER_LERP_SIZE, WORLD_BORDER_SIZE, WORLD_BORDER_WARNING_DELAY, WORLD_BORDER_WARNING_REACH, CAMERA, HELD_ITEM_CHANGE, UPDATE_VIEW_POSITION, UPDATE_VIEW_DISTANCE, SPAWN_POSITION, DISPLAY_SCOREBOARD, ENTITY_METADATA, ATTACH_ENTITY, ENTITY_VELOCITY, ENTITY_EQUIPMENT, SET_EXPERIENCE, UPDATE_HEALTH, SCOREBOARD_OBJECTIVE, SET_PASSENGERS, TEAMS, UPDATE_SCORE, UPDATE_SIMULATION_DISTANCE, SET_TITLE_SUBTITLE, TIME_UPDATE, SET_TITLE_TEXT, SET_TITLE_TIMES, ENTITY_SOUND_EFFECT, SOUND_EFFECT, CONFIGURATION_START, STOP_SOUND, SYSTEM_CHAT_MESSAGE, PLAYER_LIST_HEADER_AND_FOOTER, NBT_QUERY_RESPONSE, COLLECT_ITEM, ENTITY_TELEPORT, TICKING_STATE, TICKING_STEP, UPDATE_ADVANCEMENTS, UPDATE_ATTRIBUTES, ENTITY_EFFECT, DECLARE_RECIPES, TAGS};
   }

   static {
      long var0 = kt.a(-8277441896776855356L, 548736030393034957L, MethodHandles.lookup().lookupClass()).a(267719201524114L) ^ 100810856713450L;
      BUNDLE = new c5("BUNDLE", 0);
      SPAWN_ENTITY = new c5("SPAWN_ENTITY", 1);
      SPAWN_EXPERIENCE_ORB = new c5("SPAWN_EXPERIENCE_ORB", 2);
      ENTITY_ANIMATION = new c5("ENTITY_ANIMATION", 3);
      STATISTICS = new c5("STATISTICS", 4);
      ACKNOWLEDGE_BLOCK_CHANGES = new c5("ACKNOWLEDGE_BLOCK_CHANGES", 5);
      BLOCK_BREAK_ANIMATION = new c5("BLOCK_BREAK_ANIMATION", 6);
      BLOCK_ENTITY_DATA = new c5("BLOCK_ENTITY_DATA", 7);
      BLOCK_ACTION = new c5("BLOCK_ACTION", 8);
      BLOCK_CHANGE = new c5("BLOCK_CHANGE", 9);
      BOSS_BAR = new c5("BOSS_BAR", 10);
      SERVER_DIFFICULTY = new c5("SERVER_DIFFICULTY", 11);
      CHUNK_BATCH_END = new c5("CHUNK_BATCH_END", 12);
      CHUNK_BATCH_BEGIN = new c5("CHUNK_BATCH_BEGIN", 13);
      CHUNK_BIOMES = new c5("CHUNK_BIOMES", 14);
      CLEAR_TITLES = new c5("CLEAR_TITLES", 15);
      TAB_COMPLETE = new c5("TAB_COMPLETE", 16);
      DECLARE_COMMANDS = new c5("DECLARE_COMMANDS", 17);
      CLOSE_WINDOW = new c5("CLOSE_WINDOW", 18);
      WINDOW_ITEMS = new c5("WINDOW_ITEMS", 19);
      WINDOW_PROPERTY = new c5("WINDOW_PROPERTY", 20);
      SET_SLOT = new c5("SET_SLOT", 21);
      SET_COOLDOWN = new c5("SET_COOLDOWN", 22);
      CUSTOM_CHAT_COMPLETIONS = new c5("CUSTOM_CHAT_COMPLETIONS", 23);
      PLUGIN_MESSAGE = new c5("PLUGIN_MESSAGE", 24);
      DAMAGE_EVENT = new c5("DAMAGE_EVENT", 25);
      DELETE_CHAT = new c5("DELETE_CHAT", 26);
      DISCONNECT = new c5("DISCONNECT", 27);
      DISGUISED_CHAT = new c5("DISGUISED_CHAT", 28);
      ENTITY_STATUS = new c5("ENTITY_STATUS", 29);
      EXPLOSION = new c5("EXPLOSION", 30);
      UNLOAD_CHUNK = new c5("UNLOAD_CHUNK", 31);
      CHANGE_GAME_STATE = new c5("CHANGE_GAME_STATE", 32);
      OPEN_HORSE_WINDOW = new c5("OPEN_HORSE_WINDOW", 33);
      HURT_ANIMATION = new c5("HURT_ANIMATION", 34);
      INITIALIZE_WORLD_BORDER = new c5("INITIALIZE_WORLD_BORDER", 35);
      KEEP_ALIVE = new c5("KEEP_ALIVE", 36);
      CHUNK_DATA = new c5("CHUNK_DATA", 37);
      EFFECT = new c5("EFFECT", 38);
      PARTICLE = new c5("PARTICLE", 39);
      UPDATE_LIGHT = new c5("UPDATE_LIGHT", 40);
      JOIN_GAME = new c5("JOIN_GAME", 41);
      MAP_DATA = new c5("MAP_DATA", 42);
      MERCHANT_OFFERS = new c5("MERCHANT_OFFERS", 43);
      ENTITY_RELATIVE_MOVE = new c5("ENTITY_RELATIVE_MOVE", 44);
      ENTITY_RELATIVE_MOVE_AND_ROTATION = new c5("ENTITY_RELATIVE_MOVE_AND_ROTATION", 45);
      ENTITY_ROTATION = new c5("ENTITY_ROTATION", 46);
      VEHICLE_MOVE = new c5("VEHICLE_MOVE", 47);
      OPEN_BOOK = new c5("OPEN_BOOK", 48);
      OPEN_WINDOW = new c5("OPEN_WINDOW", 49);
      OPEN_SIGN_EDITOR = new c5("OPEN_SIGN_EDITOR", 50);
      PING = new c5("PING", 51);
      DEBUG_PONG = new c5("DEBUG_PONG", 52);
      CRAFT_RECIPE_RESPONSE = new c5("CRAFT_RECIPE_RESPONSE", 53);
      PLAYER_ABILITIES = new c5("PLAYER_ABILITIES", 54);
      CHAT_MESSAGE = new c5("CHAT_MESSAGE", 55);
      END_COMBAT_EVENT = new c5("END_COMBAT_EVENT", 56);
      ENTER_COMBAT_EVENT = new c5("ENTER_COMBAT_EVENT", 57);
      DEATH_COMBAT_EVENT = new c5("DEATH_COMBAT_EVENT", 58);
      PLAYER_INFO_REMOVE = new c5("PLAYER_INFO_REMOVE", 59);
      PLAYER_INFO_UPDATE = new c5("PLAYER_INFO_UPDATE", 60);
      FACE_PLAYER = new c5("FACE_PLAYER", 61);
      PLAYER_POSITION_AND_LOOK = new c5("PLAYER_POSITION_AND_LOOK", 62);
      UNLOCK_RECIPES = new c5("UNLOCK_RECIPES", 63);
      DESTROY_ENTITIES = new c5("DESTROY_ENTITIES", 64);
      REMOVE_ENTITY_EFFECT = new c5("REMOVE_ENTITY_EFFECT", 65);
      RESET_SCORE = new c5("RESET_SCORE", 66);
      RESOURCE_PACK_REMOVE = new c5("RESOURCE_PACK_REMOVE", 67);
      RESOURCE_PACK_SEND = new c5("RESOURCE_PACK_SEND", 68);
      RESPAWN = new c5("RESPAWN", 69);
      ENTITY_HEAD_LOOK = new c5("ENTITY_HEAD_LOOK", 70);
      MULTI_BLOCK_CHANGE = new c5("MULTI_BLOCK_CHANGE", 71);
      SELECT_ADVANCEMENTS_TAB = new c5("SELECT_ADVANCEMENTS_TAB", 72);
      SERVER_DATA = new c5("SERVER_DATA", 73);
      ACTION_BAR = new c5("ACTION_BAR", 74);
      WORLD_BORDER_CENTER = new c5("WORLD_BORDER_CENTER", 75);
      WORLD_BORDER_LERP_SIZE = new c5("WORLD_BORDER_LERP_SIZE", 76);
      WORLD_BORDER_SIZE = new c5("WORLD_BORDER_SIZE", 77);
      WORLD_BORDER_WARNING_DELAY = new c5("WORLD_BORDER_WARNING_DELAY", 78);
      WORLD_BORDER_WARNING_REACH = new c5("WORLD_BORDER_WARNING_REACH", 79);
      CAMERA = new c5("CAMERA", 80);
      HELD_ITEM_CHANGE = new c5("HELD_ITEM_CHANGE", 81);
      UPDATE_VIEW_POSITION = new c5("UPDATE_VIEW_POSITION", 82);
      UPDATE_VIEW_DISTANCE = new c5("UPDATE_VIEW_DISTANCE", 83);
      SPAWN_POSITION = new c5("SPAWN_POSITION", 84);
      DISPLAY_SCOREBOARD = new c5("DISPLAY_SCOREBOARD", 85);
      ENTITY_METADATA = new c5("ENTITY_METADATA", 86);
      ATTACH_ENTITY = new c5("ATTACH_ENTITY", 87);
      ENTITY_VELOCITY = new c5("ENTITY_VELOCITY", 88);
      ENTITY_EQUIPMENT = new c5("ENTITY_EQUIPMENT", 89);
      SET_EXPERIENCE = new c5("SET_EXPERIENCE", 90);
      UPDATE_HEALTH = new c5("UPDATE_HEALTH", 91);
      SCOREBOARD_OBJECTIVE = new c5("SCOREBOARD_OBJECTIVE", 92);
      SET_PASSENGERS = new c5("SET_PASSENGERS", 93);
      TEAMS = new c5("TEAMS", 94);
      UPDATE_SCORE = new c5("UPDATE_SCORE", 95);
      UPDATE_SIMULATION_DISTANCE = new c5("UPDATE_SIMULATION_DISTANCE", 96);
      SET_TITLE_SUBTITLE = new c5("SET_TITLE_SUBTITLE", 97);
      TIME_UPDATE = new c5("TIME_UPDATE", 98);
      SET_TITLE_TEXT = new c5("SET_TITLE_TEXT", 99);
      SET_TITLE_TIMES = new c5("SET_TITLE_TIMES", 100);
      ENTITY_SOUND_EFFECT = new c5("ENTITY_SOUND_EFFECT", 101);
      SOUND_EFFECT = new c5("SOUND_EFFECT", 102);
      CONFIGURATION_START = new c5("CONFIGURATION_START", 103);
      STOP_SOUND = new c5("STOP_SOUND", 104);
      SYSTEM_CHAT_MESSAGE = new c5("SYSTEM_CHAT_MESSAGE", 105);
      PLAYER_LIST_HEADER_AND_FOOTER = new c5("PLAYER_LIST_HEADER_AND_FOOTER", 106);
      NBT_QUERY_RESPONSE = new c5("NBT_QUERY_RESPONSE", 107);
      COLLECT_ITEM = new c5("COLLECT_ITEM", 108);
      ENTITY_TELEPORT = new c5("ENTITY_TELEPORT", 109);
      TICKING_STATE = new c5("TICKING_STATE", 110);
      TICKING_STEP = new c5("TICKING_STEP", 111);
      UPDATE_ADVANCEMENTS = new c5("UPDATE_ADVANCEMENTS", 112);
      UPDATE_ATTRIBUTES = new c5("UPDATE_ATTRIBUTES", 113);
      ENTITY_EFFECT = new c5("ENTITY_EFFECT", 114);
      DECLARE_RECIPES = new c5("DECLARE_RECIPES", 115);
      TAGS = new c5("TAGS", 116);
   }
}
