package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum E0 {
   TELEPORT_CONFIRM,
   QUERY_BLOCK_NBT,
   SELECT_BUNDLE_ITEM,
   SET_DIFFICULTY,
   CHAT_ACK,
   CHAT_COMMAND_UNSIGNED,
   CHAT_COMMAND,
   CHAT_MESSAGE,
   CHAT_SESSION_UPDATE,
   CHUNK_BATCH_ACK,
   CLIENT_STATUS,
   CLIENT_TICK_END,
   CLIENT_SETTINGS,
   TAB_COMPLETE,
   CONFIGURATION_ACK,
   CLICK_WINDOW_BUTTON,
   CLICK_WINDOW,
   CLOSE_WINDOW,
   SLOT_STATE_CHANGE,
   COOKIE_RESPONSE,
   PLUGIN_MESSAGE,
   DEBUG_SAMPLE_SUBSCRIPTION,
   EDIT_BOOK,
   QUERY_ENTITY_NBT,
   INTERACT_ENTITY,
   GENERATE_STRUCTURE,
   KEEP_ALIVE,
   LOCK_DIFFICULTY,
   PLAYER_POSITION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_ROTATION,
   PLAYER_FLYING,
   VEHICLE_MOVE,
   STEER_BOAT,
   PICK_ITEM,
   DEBUG_PING,
   CRAFT_RECIPE_REQUEST,
   PLAYER_ABILITIES,
   PLAYER_DIGGING,
   ENTITY_ACTION,
   PLAYER_INPUT,
   PONG,
   SET_RECIPE_BOOK_STATE,
   SET_DISPLAYED_RECIPE,
   NAME_ITEM,
   RESOURCE_PACK_STATUS,
   ADVANCEMENT_TAB,
   SELECT_TRADE,
   SET_BEACON_EFFECT,
   HELD_ITEM_CHANGE,
   UPDATE_COMMAND_BLOCK,
   UPDATE_COMMAND_BLOCK_MINECART,
   CREATIVE_INVENTORY_ACTION,
   UPDATE_JIGSAW_BLOCK,
   UPDATE_STRUCTURE_BLOCK,
   UPDATE_SIGN,
   ANIMATION,
   SPECTATE,
   PLAYER_BLOCK_PLACEMENT,
   USE_ITEM;

   // $FF: synthetic method
   private static E0[] w() {
      return new E0[]{TELEPORT_CONFIRM, QUERY_BLOCK_NBT, SELECT_BUNDLE_ITEM, SET_DIFFICULTY, CHAT_ACK, CHAT_COMMAND_UNSIGNED, CHAT_COMMAND, CHAT_MESSAGE, CHAT_SESSION_UPDATE, CHUNK_BATCH_ACK, CLIENT_STATUS, CLIENT_TICK_END, CLIENT_SETTINGS, TAB_COMPLETE, CONFIGURATION_ACK, CLICK_WINDOW_BUTTON, CLICK_WINDOW, CLOSE_WINDOW, SLOT_STATE_CHANGE, COOKIE_RESPONSE, PLUGIN_MESSAGE, DEBUG_SAMPLE_SUBSCRIPTION, EDIT_BOOK, QUERY_ENTITY_NBT, INTERACT_ENTITY, GENERATE_STRUCTURE, KEEP_ALIVE, LOCK_DIFFICULTY, PLAYER_POSITION, PLAYER_POSITION_AND_ROTATION, PLAYER_ROTATION, PLAYER_FLYING, VEHICLE_MOVE, STEER_BOAT, PICK_ITEM, DEBUG_PING, CRAFT_RECIPE_REQUEST, PLAYER_ABILITIES, PLAYER_DIGGING, ENTITY_ACTION, PLAYER_INPUT, PONG, SET_RECIPE_BOOK_STATE, SET_DISPLAYED_RECIPE, NAME_ITEM, RESOURCE_PACK_STATUS, ADVANCEMENT_TAB, SELECT_TRADE, SET_BEACON_EFFECT, HELD_ITEM_CHANGE, UPDATE_COMMAND_BLOCK, UPDATE_COMMAND_BLOCK_MINECART, CREATIVE_INVENTORY_ACTION, UPDATE_JIGSAW_BLOCK, UPDATE_STRUCTURE_BLOCK, UPDATE_SIGN, ANIMATION, SPECTATE, PLAYER_BLOCK_PLACEMENT, USE_ITEM};
   }

   static {
      long var0 = kt.a(338104969378089188L, 907205116854166694L, MethodHandles.lookup().lookupClass()).a(260263753384022L) ^ 39149299267176L;
      TELEPORT_CONFIRM = new E0("TELEPORT_CONFIRM", 0);
      QUERY_BLOCK_NBT = new E0("QUERY_BLOCK_NBT", 1);
      SELECT_BUNDLE_ITEM = new E0("SELECT_BUNDLE_ITEM", 2);
      SET_DIFFICULTY = new E0("SET_DIFFICULTY", 3);
      CHAT_ACK = new E0("CHAT_ACK", 4);
      CHAT_COMMAND_UNSIGNED = new E0("CHAT_COMMAND_UNSIGNED", 5);
      CHAT_COMMAND = new E0("CHAT_COMMAND", 6);
      CHAT_MESSAGE = new E0("CHAT_MESSAGE", 7);
      CHAT_SESSION_UPDATE = new E0("CHAT_SESSION_UPDATE", 8);
      CHUNK_BATCH_ACK = new E0("CHUNK_BATCH_ACK", 9);
      CLIENT_STATUS = new E0("CLIENT_STATUS", 10);
      CLIENT_TICK_END = new E0("CLIENT_TICK_END", 11);
      CLIENT_SETTINGS = new E0("CLIENT_SETTINGS", 12);
      TAB_COMPLETE = new E0("TAB_COMPLETE", 13);
      CONFIGURATION_ACK = new E0("CONFIGURATION_ACK", 14);
      CLICK_WINDOW_BUTTON = new E0("CLICK_WINDOW_BUTTON", 15);
      CLICK_WINDOW = new E0("CLICK_WINDOW", 16);
      CLOSE_WINDOW = new E0("CLOSE_WINDOW", 17);
      SLOT_STATE_CHANGE = new E0("SLOT_STATE_CHANGE", 18);
      COOKIE_RESPONSE = new E0("COOKIE_RESPONSE", 19);
      PLUGIN_MESSAGE = new E0("PLUGIN_MESSAGE", 20);
      DEBUG_SAMPLE_SUBSCRIPTION = new E0("DEBUG_SAMPLE_SUBSCRIPTION", 21);
      EDIT_BOOK = new E0("EDIT_BOOK", 22);
      QUERY_ENTITY_NBT = new E0("QUERY_ENTITY_NBT", 23);
      INTERACT_ENTITY = new E0("INTERACT_ENTITY", 24);
      GENERATE_STRUCTURE = new E0("GENERATE_STRUCTURE", 25);
      KEEP_ALIVE = new E0("KEEP_ALIVE", 26);
      LOCK_DIFFICULTY = new E0("LOCK_DIFFICULTY", 27);
      PLAYER_POSITION = new E0("PLAYER_POSITION", 28);
      PLAYER_POSITION_AND_ROTATION = new E0("PLAYER_POSITION_AND_ROTATION", 29);
      PLAYER_ROTATION = new E0("PLAYER_ROTATION", 30);
      PLAYER_FLYING = new E0("PLAYER_FLYING", 31);
      VEHICLE_MOVE = new E0("VEHICLE_MOVE", 32);
      STEER_BOAT = new E0("STEER_BOAT", 33);
      PICK_ITEM = new E0("PICK_ITEM", 34);
      DEBUG_PING = new E0("DEBUG_PING", 35);
      CRAFT_RECIPE_REQUEST = new E0("CRAFT_RECIPE_REQUEST", 36);
      PLAYER_ABILITIES = new E0("PLAYER_ABILITIES", 37);
      PLAYER_DIGGING = new E0("PLAYER_DIGGING", 38);
      ENTITY_ACTION = new E0("ENTITY_ACTION", 39);
      PLAYER_INPUT = new E0("PLAYER_INPUT", 40);
      PONG = new E0("PONG", 41);
      SET_RECIPE_BOOK_STATE = new E0("SET_RECIPE_BOOK_STATE", 42);
      SET_DISPLAYED_RECIPE = new E0("SET_DISPLAYED_RECIPE", 43);
      NAME_ITEM = new E0("NAME_ITEM", 44);
      RESOURCE_PACK_STATUS = new E0("RESOURCE_PACK_STATUS", 45);
      ADVANCEMENT_TAB = new E0("ADVANCEMENT_TAB", 46);
      SELECT_TRADE = new E0("SELECT_TRADE", 47);
      SET_BEACON_EFFECT = new E0("SET_BEACON_EFFECT", 48);
      HELD_ITEM_CHANGE = new E0("HELD_ITEM_CHANGE", 49);
      UPDATE_COMMAND_BLOCK = new E0("UPDATE_COMMAND_BLOCK", 50);
      UPDATE_COMMAND_BLOCK_MINECART = new E0("UPDATE_COMMAND_BLOCK_MINECART", 51);
      CREATIVE_INVENTORY_ACTION = new E0("CREATIVE_INVENTORY_ACTION", 52);
      UPDATE_JIGSAW_BLOCK = new E0("UPDATE_JIGSAW_BLOCK", 53);
      UPDATE_STRUCTURE_BLOCK = new E0("UPDATE_STRUCTURE_BLOCK", 54);
      UPDATE_SIGN = new E0("UPDATE_SIGN", 55);
      ANIMATION = new E0("ANIMATION", 56);
      SPECTATE = new E0("SPECTATE", 57);
      PLAYER_BLOCK_PLACEMENT = new E0("PLAYER_BLOCK_PLACEMENT", 58);
      USE_ITEM = new E0("USE_ITEM", 59);
   }
}
