package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum G7 {
   BLOCKED,
   OPEN,
   WALKABLE,
   WALKABLE_DOOR,
   TRAPDOOR,
   POWDER_SNOW,
   DANGER_POWDER_SNOW,
   FENCE,
   LAVA,
   WATER,
   WATER_BORDER,
   RAIL,
   UNPASSABLE_RAIL,
   DANGER_FIRE,
   DAMAGE_FIRE,
   DANGER_OTHER,
   DAMAGE_OTHER,
   DOOR_OPEN,
   DOOR_WOOD_CLOSED,
   DOOR_IRON_CLOSED,
   BREACH,
   LEAVES,
   STICKY_HONEY,
   COCOA,
   DAMAGE_CAUTIOUS,
   DANGER_TRAPDOOR;

   // $FF: synthetic method
   private static G7[] w() {
      return new G7[]{BLOCKED, OPEN, WALKABLE, WALKABLE_DOOR, TRAPDOOR, POWDER_SNOW, DANGER_POWDER_SNOW, FENCE, LAVA, WATER, WATER_BORDER, RAIL, UNPASSABLE_RAIL, DANGER_FIRE, DAMAGE_FIRE, DANGER_OTHER, DAMAGE_OTHER, DOOR_OPEN, DOOR_WOOD_CLOSED, DOOR_IRON_CLOSED, BREACH, LEAVES, STICKY_HONEY, COCOA, DAMAGE_CAUTIOUS, DANGER_TRAPDOOR};
   }

   static {
      long var0 = kt.a(-4958416041731523930L, 7677282952459484424L, MethodHandles.lookup().lookupClass()).a(279357999538449L) ^ 140607852598913L;
      BLOCKED = new G7("BLOCKED", 0);
      OPEN = new G7("OPEN", 1);
      WALKABLE = new G7("WALKABLE", 2);
      WALKABLE_DOOR = new G7("WALKABLE_DOOR", 3);
      TRAPDOOR = new G7("TRAPDOOR", 4);
      POWDER_SNOW = new G7("POWDER_SNOW", 5);
      DANGER_POWDER_SNOW = new G7("DANGER_POWDER_SNOW", 6);
      FENCE = new G7("FENCE", 7);
      LAVA = new G7("LAVA", 8);
      WATER = new G7("WATER", 9);
      WATER_BORDER = new G7("WATER_BORDER", 10);
      RAIL = new G7("RAIL", 11);
      UNPASSABLE_RAIL = new G7("UNPASSABLE_RAIL", 12);
      DANGER_FIRE = new G7("DANGER_FIRE", 13);
      DAMAGE_FIRE = new G7("DAMAGE_FIRE", 14);
      DANGER_OTHER = new G7("DANGER_OTHER", 15);
      DAMAGE_OTHER = new G7("DAMAGE_OTHER", 16);
      DOOR_OPEN = new G7("DOOR_OPEN", 17);
      DOOR_WOOD_CLOSED = new G7("DOOR_WOOD_CLOSED", 18);
      DOOR_IRON_CLOSED = new G7("DOOR_IRON_CLOSED", 19);
      BREACH = new G7("BREACH", 20);
      LEAVES = new G7("LEAVES", 21);
      STICKY_HONEY = new G7("STICKY_HONEY", 22);
      COCOA = new G7("COCOA", 23);
      DAMAGE_CAUTIOUS = new G7("DAMAGE_CAUTIOUS", 24);
      DANGER_TRAPDOOR = new G7("DANGER_TRAPDOOR", 25);
   }
}
