package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum G9 {
   PLUGIN_MESSAGE,
   DISCONNECT,
   CONFIGURATION_END,
   KEEP_ALIVE,
   PING,
   REGISTRY_DATA,
   RESOURCE_PACK_REMOVE,
   RESOURCE_PACK_SEND,
   UPDATE_ENABLED_FEATURES,
   UPDATE_TAGS;

   // $FF: synthetic method
   private static G9[] f() {
      return new G9[]{PLUGIN_MESSAGE, DISCONNECT, CONFIGURATION_END, KEEP_ALIVE, PING, REGISTRY_DATA, RESOURCE_PACK_REMOVE, RESOURCE_PACK_SEND, UPDATE_ENABLED_FEATURES, UPDATE_TAGS};
   }

   static {
      long var0 = kt.a(4092473026153929666L, 7424789069118366658L, MethodHandles.lookup().lookupClass()).a(243444428812094L) ^ 117728514118129L;
      PLUGIN_MESSAGE = new G9("PLUGIN_MESSAGE", 0);
      DISCONNECT = new G9("DISCONNECT", 1);
      CONFIGURATION_END = new G9("CONFIGURATION_END", 2);
      KEEP_ALIVE = new G9("KEEP_ALIVE", 3);
      PING = new G9("PING", 4);
      REGISTRY_DATA = new G9("REGISTRY_DATA", 5);
      RESOURCE_PACK_REMOVE = new G9("RESOURCE_PACK_REMOVE", 6);
      RESOURCE_PACK_SEND = new G9("RESOURCE_PACK_SEND", 7);
      UPDATE_ENABLED_FEATURES = new G9("UPDATE_ENABLED_FEATURES", 8);
      UPDATE_TAGS = new G9("UPDATE_TAGS", 9);
   }
}
