package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum GE {
   TELEPORT_CONFIRM,
   QUERY_BLOCK_NBT,
   SET_DIFFICULTY,
   CHAT_MESSAGE,
   CLIENT_STATUS,
   CLIENT_SETTINGS,
   TAB_COMPLETE,
   WINDOW_CONFIRMATION,
   CLICK_WINDOW_BUTTON,
   CLICK_WINDOW,
   CLOSE_WINDOW,
   PLUGIN_MESSAGE,
   EDIT_BOOK,
   QUERY_ENTITY_NBT,
   INTERACT_ENTITY,
   GENERATE_STRUCTURE,
   KEEP_ALIVE,
   LOCK_DIFFICULTY,
   PLAYER_POSITION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_ROTATION,
   PLAYER_FLYING,
   VEHICLE_MOVE,
   STEER_BOAT,
   PICK_ITEM,
   CRAFT_RECIPE_REQUEST,
   PLAYER_ABILITIES,
   PLAYER_DIGGING,
   ENTITY_ACTION,
   STEER_VEHICLE,
   RECIPE_BOOK_DATA,
   NAME_ITEM,
   RESOURCE_PACK_STATUS,
   ADVANCEMENT_TAB,
   SELECT_TRADE,
   SET_BEACON_EFFECT,
   HELD_ITEM_CHANGE,
   UPDATE_COMMAND_BLOCK,
   UPDATE_COMMAND_BLOCK_MINECART,
   CREATIVE_INVENTORY_ACTION,
   UPDATE_JIGSAW_BLOCK,
   UPDATE_STRUCTURE_BLOCK,
   UPDATE_SIGN,
   ANIMATION,
   SPECTATE,
   PLAYER_BLOCK_PLACEMENT,
   USE_ITEM;

   // $FF: synthetic method
   private static GE[] B() {
      return new GE[]{TELEPORT_CONFIRM, QUERY_BLOCK_NBT, SET_DIFFICULTY, CHAT_MESSAGE, CLIENT_STATUS, CLIENT_SETTINGS, TAB_COMPLETE, WINDOW_CONFIRMATION, CLICK_WINDOW_BUTTON, CLICK_WINDOW, CLOSE_WINDOW, PLUGIN_MESSAGE, EDIT_BOOK, QUERY_ENTITY_NBT, INTERACT_ENTITY, GENERATE_STRUCTURE, KEEP_ALIVE, LOCK_DIFFICULTY, PLAYER_POSITION, PLAYER_POSITION_AND_ROTATION, PLAYER_ROTATION, PLAYER_FLYING, VEHICLE_MOVE, STEER_BOAT, PICK_ITEM, CRAFT_RECIPE_REQUEST, PLAYER_ABILITIES, PLAYER_DIGGING, ENTITY_ACTION, STEER_VEHICLE, RECIPE_BOOK_DATA, NAME_ITEM, RESOURCE_PACK_STATUS, ADVANCEMENT_TAB, SELECT_TRADE, SET_BEACON_EFFECT, HELD_ITEM_CHANGE, UPDATE_COMMAND_BLOCK, UPDATE_COMMAND_BLOCK_MINECART, CREATIVE_INVENTORY_ACTION, UPDATE_JIGSAW_BLOCK, UPDATE_STRUCTURE_BLOCK, UPDATE_SIGN, ANIMATION, SPECTATE, PLAYER_BLOCK_PLACEMENT, USE_ITEM};
   }

   static {
      long var0 = kt.a(1420037510037265765L, 7521295767884511493L, MethodHandles.lookup().lookupClass()).a(98013947298073L) ^ 101400796498808L;
      TELEPORT_CONFIRM = new GE("TELEPORT_CONFIRM", 0);
      QUERY_BLOCK_NBT = new GE("QUERY_BLOCK_NBT", 1);
      SET_DIFFICULTY = new GE("SET_DIFFICULTY", 2);
      CHAT_MESSAGE = new GE("CHAT_MESSAGE", 3);
      CLIENT_STATUS = new GE("CLIENT_STATUS", 4);
      CLIENT_SETTINGS = new GE("CLIENT_SETTINGS", 5);
      TAB_COMPLETE = new GE("TAB_COMPLETE", 6);
      WINDOW_CONFIRMATION = new GE("WINDOW_CONFIRMATION", 7);
      CLICK_WINDOW_BUTTON = new GE("CLICK_WINDOW_BUTTON", 8);
      CLICK_WINDOW = new GE("CLICK_WINDOW", 9);
      CLOSE_WINDOW = new GE("CLOSE_WINDOW", 10);
      PLUGIN_MESSAGE = new GE("PLUGIN_MESSAGE", 11);
      EDIT_BOOK = new GE("EDIT_BOOK", 12);
      QUERY_ENTITY_NBT = new GE("QUERY_ENTITY_NBT", 13);
      INTERACT_ENTITY = new GE("INTERACT_ENTITY", 14);
      GENERATE_STRUCTURE = new GE("GENERATE_STRUCTURE", 15);
      KEEP_ALIVE = new GE("KEEP_ALIVE", 16);
      LOCK_DIFFICULTY = new GE("LOCK_DIFFICULTY", 17);
      PLAYER_POSITION = new GE("PLAYER_POSITION", 18);
      PLAYER_POSITION_AND_ROTATION = new GE("PLAYER_POSITION_AND_ROTATION", 19);
      PLAYER_ROTATION = new GE("PLAYER_ROTATION", 20);
      PLAYER_FLYING = new GE("PLAYER_FLYING", 21);
      VEHICLE_MOVE = new GE("VEHICLE_MOVE", 22);
      STEER_BOAT = new GE("STEER_BOAT", 23);
      PICK_ITEM = new GE("PICK_ITEM", 24);
      CRAFT_RECIPE_REQUEST = new GE("CRAFT_RECIPE_REQUEST", 25);
      PLAYER_ABILITIES = new GE("PLAYER_ABILITIES", 26);
      PLAYER_DIGGING = new GE("PLAYER_DIGGING", 27);
      ENTITY_ACTION = new GE("ENTITY_ACTION", 28);
      STEER_VEHICLE = new GE("STEER_VEHICLE", 29);
      RECIPE_BOOK_DATA = new GE("RECIPE_BOOK_DATA", 30);
      NAME_ITEM = new GE("NAME_ITEM", 31);
      RESOURCE_PACK_STATUS = new GE("RESOURCE_PACK_STATUS", 32);
      ADVANCEMENT_TAB = new GE("ADVANCEMENT_TAB", 33);
      SELECT_TRADE = new GE("SELECT_TRADE", 34);
      SET_BEACON_EFFECT = new GE("SET_BEACON_EFFECT", 35);
      HELD_ITEM_CHANGE = new GE("HELD_ITEM_CHANGE", 36);
      UPDATE_COMMAND_BLOCK = new GE("UPDATE_COMMAND_BLOCK", 37);
      UPDATE_COMMAND_BLOCK_MINECART = new GE("UPDATE_COMMAND_BLOCK_MINECART", 38);
      CREATIVE_INVENTORY_ACTION = new GE("CREATIVE_INVENTORY_ACTION", 39);
      UPDATE_JIGSAW_BLOCK = new GE("UPDATE_JIGSAW_BLOCK", 40);
      UPDATE_STRUCTURE_BLOCK = new GE("UPDATE_STRUCTURE_BLOCK", 41);
      UPDATE_SIGN = new GE("UPDATE_SIGN", 42);
      ANIMATION = new GE("ANIMATION", 43);
      SPECTATE = new GE("SPECTATE", 44);
      PLAYER_BLOCK_PLACEMENT = new GE("PLAYER_BLOCK_PLACEMENT", 45);
      USE_ITEM = new GE("USE_ITEM", 46);
   }
}
