package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum Gv {
   TELEPORT_CONFIRM,
   QUERY_BLOCK_NBT,
   SET_DIFFICULTY,
   CHAT_COMMAND,
   CHAT_MESSAGE,
   CHAT_PREVIEW,
   CLIENT_STATUS,
   CLIENT_SETTINGS,
   TAB_COMPLETE,
   CLICK_WINDOW_BUTTON,
   CLICK_WINDOW,
   CLOSE_WINDOW,
   PLUGIN_MESSAGE,
   EDIT_BOOK,
   QUERY_ENTITY_NBT,
   INTERACT_ENTITY,
   GENERATE_STRUCTURE,
   KEEP_ALIVE,
   LOCK_DIFFICULTY,
   PLAYER_POSITION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_ROTATION,
   PLAYER_FLYING,
   VEHICLE_MOVE,
   STEER_BOAT,
   PICK_ITEM,
   CRAFT_RECIPE_REQUEST,
   PLAYER_ABILITIES,
   PLAYER_DIGGING,
   ENTITY_ACTION,
   STEER_VEHICLE,
   PONG,
   SET_RECIPE_BOOK_STATE,
   SET_DISPLAYED_RECIPE,
   NAME_ITEM,
   RESOURCE_PACK_STATUS,
   ADVANCEMENT_TAB,
   SELECT_TRADE,
   SET_BEACON_EFFECT,
   HELD_ITEM_CHANGE,
   UPDATE_COMMAND_BLOCK,
   UPDATE_COMMAND_BLOCK_MINECART,
   CREATIVE_INVENTORY_ACTION,
   UPDATE_JIGSAW_BLOCK,
   UPDATE_STRUCTURE_BLOCK,
   UPDATE_SIGN,
   ANIMATION,
   SPECTATE,
   PLAYER_BLOCK_PLACEMENT,
   USE_ITEM;

   // $FF: synthetic method
   private static Gv[] e() {
      return new Gv[]{TELEPORT_CONFIRM, QUERY_BLOCK_NBT, SET_DIFFICULTY, CHAT_COMMAND, CHAT_MESSAGE, CHAT_PREVIEW, CLIENT_STATUS, CLIENT_SETTINGS, TAB_COMPLETE, CLICK_WINDOW_BUTTON, CLICK_WINDOW, CLOSE_WINDOW, PLUGIN_MESSAGE, EDIT_BOOK, QUERY_ENTITY_NBT, INTERACT_ENTITY, GENERATE_STRUCTURE, KEEP_ALIVE, LOCK_DIFFICULTY, PLAYER_POSITION, PLAYER_POSITION_AND_ROTATION, PLAYER_ROTATION, PLAYER_FLYING, VEHICLE_MOVE, STEER_BOAT, PICK_ITEM, CRAFT_RECIPE_REQUEST, PLAYER_ABILITIES, PLAYER_DIGGING, ENTITY_ACTION, STEER_VEHICLE, PONG, SET_RECIPE_BOOK_STATE, SET_DISPLAYED_RECIPE, NAME_ITEM, RESOURCE_PACK_STATUS, ADVANCEMENT_TAB, SELECT_TRADE, SET_BEACON_EFFECT, HELD_ITEM_CHANGE, UPDATE_COMMAND_BLOCK, UPDATE_COMMAND_BLOCK_MINECART, CREATIVE_INVENTORY_ACTION, UPDATE_JIGSAW_BLOCK, UPDATE_STRUCTURE_BLOCK, UPDATE_SIGN, ANIMATION, SPECTATE, PLAYER_BLOCK_PLACEMENT, USE_ITEM};
   }

   static {
      long var0 = kt.a(-4086349578457187040L, -1581227810364085177L, MethodHandles.lookup().lookupClass()).a(187538765221328L) ^ 30939533955817L;
      TELEPORT_CONFIRM = new Gv("TELEPORT_CONFIRM", 0);
      QUERY_BLOCK_NBT = new Gv("QUERY_BLOCK_NBT", 1);
      SET_DIFFICULTY = new Gv("SET_DIFFICULTY", 2);
      CHAT_COMMAND = new Gv("CHAT_COMMAND", 3);
      CHAT_MESSAGE = new Gv("CHAT_MESSAGE", 4);
      CHAT_PREVIEW = new Gv("CHAT_PREVIEW", 5);
      CLIENT_STATUS = new Gv("CLIENT_STATUS", 6);
      CLIENT_SETTINGS = new Gv("CLIENT_SETTINGS", 7);
      TAB_COMPLETE = new Gv("TAB_COMPLETE", 8);
      CLICK_WINDOW_BUTTON = new Gv("CLICK_WINDOW_BUTTON", 9);
      CLICK_WINDOW = new Gv("CLICK_WINDOW", 10);
      CLOSE_WINDOW = new Gv("CLOSE_WINDOW", 11);
      PLUGIN_MESSAGE = new Gv("PLUGIN_MESSAGE", 12);
      EDIT_BOOK = new Gv("EDIT_BOOK", 13);
      QUERY_ENTITY_NBT = new Gv("QUERY_ENTITY_NBT", 14);
      INTERACT_ENTITY = new Gv("INTERACT_ENTITY", 15);
      GENERATE_STRUCTURE = new Gv("GENERATE_STRUCTURE", 16);
      KEEP_ALIVE = new Gv("KEEP_ALIVE", 17);
      LOCK_DIFFICULTY = new Gv("LOCK_DIFFICULTY", 18);
      PLAYER_POSITION = new Gv("PLAYER_POSITION", 19);
      PLAYER_POSITION_AND_ROTATION = new Gv("PLAYER_POSITION_AND_ROTATION", 20);
      PLAYER_ROTATION = new Gv("PLAYER_ROTATION", 21);
      PLAYER_FLYING = new Gv("PLAYER_FLYING", 22);
      VEHICLE_MOVE = new Gv("VEHICLE_MOVE", 23);
      STEER_BOAT = new Gv("STEER_BOAT", 24);
      PICK_ITEM = new Gv("PICK_ITEM", 25);
      CRAFT_RECIPE_REQUEST = new Gv("CRAFT_RECIPE_REQUEST", 26);
      PLAYER_ABILITIES = new Gv("PLAYER_ABILITIES", 27);
      PLAYER_DIGGING = new Gv("PLAYER_DIGGING", 28);
      ENTITY_ACTION = new Gv("ENTITY_ACTION", 29);
      STEER_VEHICLE = new Gv("STEER_VEHICLE", 30);
      PONG = new Gv("PONG", 31);
      SET_RECIPE_BOOK_STATE = new Gv("SET_RECIPE_BOOK_STATE", 32);
      SET_DISPLAYED_RECIPE = new Gv("SET_DISPLAYED_RECIPE", 33);
      NAME_ITEM = new Gv("NAME_ITEM", 34);
      RESOURCE_PACK_STATUS = new Gv("RESOURCE_PACK_STATUS", 35);
      ADVANCEMENT_TAB = new Gv("ADVANCEMENT_TAB", 36);
      SELECT_TRADE = new Gv("SELECT_TRADE", 37);
      SET_BEACON_EFFECT = new Gv("SET_BEACON_EFFECT", 38);
      HELD_ITEM_CHANGE = new Gv("HELD_ITEM_CHANGE", 39);
      UPDATE_COMMAND_BLOCK = new Gv("UPDATE_COMMAND_BLOCK", 40);
      UPDATE_COMMAND_BLOCK_MINECART = new Gv("UPDATE_COMMAND_BLOCK_MINECART", 41);
      CREATIVE_INVENTORY_ACTION = new Gv("CREATIVE_INVENTORY_ACTION", 42);
      UPDATE_JIGSAW_BLOCK = new Gv("UPDATE_JIGSAW_BLOCK", 43);
      UPDATE_STRUCTURE_BLOCK = new Gv("UPDATE_STRUCTURE_BLOCK", 44);
      UPDATE_SIGN = new Gv("UPDATE_SIGN", 45);
      ANIMATION = new Gv("ANIMATION", 46);
      SPECTATE = new Gv("SPECTATE", 47);
      PLAYER_BLOCK_PLACEMENT = new Gv("PLAYER_BLOCK_PLACEMENT", 48);
      USE_ITEM = new Gv("USE_ITEM", 49);
   }
}
