package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum mR {
   TELEPORT_CONFIRM,
   QUERY_BLOCK_NBT,
   SET_DIFFICULTY,
   CHAT_ACK,
   CHAT_COMMAND,
   CHAT_MESSAGE,
   CHAT_SESSION_UPDATE,
   CLIENT_STATUS,
   CLIENT_SETTINGS,
   TAB_COMPLETE,
   CLICK_WINDOW_BUTTON,
   CLICK_WINDOW,
   CLOSE_WINDOW,
   PLUGIN_MESSAGE,
   EDIT_BOOK,
   QUERY_ENTITY_NBT,
   INTERACT_ENTITY,
   GENERATE_STRUCTURE,
   KEEP_ALIVE,
   LOCK_DIFFICULTY,
   PLAYER_POSITION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_ROTATION,
   PLAYER_FLYING,
   VEHICLE_MOVE,
   STEER_BOAT,
   PICK_ITEM,
   CRAFT_RECIPE_REQUEST,
   PLAYER_ABILITIES,
   PLAYER_DIGGING,
   ENTITY_ACTION,
   STEER_VEHICLE,
   PONG,
   SET_RECIPE_BOOK_STATE,
   SET_DISPLAYED_RECIPE,
   NAME_ITEM,
   RESOURCE_PACK_STATUS,
   ADVANCEMENT_TAB,
   SELECT_TRADE,
   SET_BEACON_EFFECT,
   HELD_ITEM_CHANGE,
   UPDATE_COMMAND_BLOCK,
   UPDATE_COMMAND_BLOCK_MINECART,
   CREATIVE_INVENTORY_ACTION,
   UPDATE_JIGSAW_BLOCK,
   UPDATE_STRUCTURE_BLOCK,
   UPDATE_SIGN,
   ANIMATION,
   SPECTATE,
   PLAYER_BLOCK_PLACEMENT,
   USE_ITEM;

   // $FF: synthetic method
   private static mR[] S() {
      return new mR[]{TELEPORT_CONFIRM, QUERY_BLOCK_NBT, SET_DIFFICULTY, CHAT_ACK, CHAT_COMMAND, CHAT_MESSAGE, CHAT_SESSION_UPDATE, CLIENT_STATUS, CLIENT_SETTINGS, TAB_COMPLETE, CLICK_WINDOW_BUTTON, CLICK_WINDOW, CLOSE_WINDOW, PLUGIN_MESSAGE, EDIT_BOOK, QUERY_ENTITY_NBT, INTERACT_ENTITY, GENERATE_STRUCTURE, KEEP_ALIVE, LOCK_DIFFICULTY, PLAYER_POSITION, PLAYER_POSITION_AND_ROTATION, PLAYER_ROTATION, PLAYER_FLYING, VEHICLE_MOVE, STEER_BOAT, PICK_ITEM, CRAFT_RECIPE_REQUEST, PLAYER_ABILITIES, PLAYER_DIGGING, ENTITY_ACTION, STEER_VEHICLE, PONG, SET_RECIPE_BOOK_STATE, SET_DISPLAYED_RECIPE, NAME_ITEM, RESOURCE_PACK_STATUS, ADVANCEMENT_TAB, SELECT_TRADE, SET_BEACON_EFFECT, HELD_ITEM_CHANGE, UPDATE_COMMAND_BLOCK, UPDATE_COMMAND_BLOCK_MINECART, CREATIVE_INVENTORY_ACTION, UPDATE_JIGSAW_BLOCK, UPDATE_STRUCTURE_BLOCK, UPDATE_SIGN, ANIMATION, SPECTATE, PLAYER_BLOCK_PLACEMENT, USE_ITEM};
   }

   static {
      long var0 = kt.a(2261429750414028169L, -4124965110760763320L, MethodHandles.lookup().lookupClass()).a(162716218462684L) ^ 35019138812292L;
      TELEPORT_CONFIRM = new mR("TELEPORT_CONFIRM", 0);
      QUERY_BLOCK_NBT = new mR("QUERY_BLOCK_NBT", 1);
      SET_DIFFICULTY = new mR("SET_DIFFICULTY", 2);
      CHAT_ACK = new mR("CHAT_ACK", 3);
      CHAT_COMMAND = new mR("CHAT_COMMAND", 4);
      CHAT_MESSAGE = new mR("CHAT_MESSAGE", 5);
      CHAT_SESSION_UPDATE = new mR("CHAT_SESSION_UPDATE", 6);
      CLIENT_STATUS = new mR("CLIENT_STATUS", 7);
      CLIENT_SETTINGS = new mR("CLIENT_SETTINGS", 8);
      TAB_COMPLETE = new mR("TAB_COMPLETE", 9);
      CLICK_WINDOW_BUTTON = new mR("CLICK_WINDOW_BUTTON", 10);
      CLICK_WINDOW = new mR("CLICK_WINDOW", 11);
      CLOSE_WINDOW = new mR("CLOSE_WINDOW", 12);
      PLUGIN_MESSAGE = new mR("PLUGIN_MESSAGE", 13);
      EDIT_BOOK = new mR("EDIT_BOOK", 14);
      QUERY_ENTITY_NBT = new mR("QUERY_ENTITY_NBT", 15);
      INTERACT_ENTITY = new mR("INTERACT_ENTITY", 16);
      GENERATE_STRUCTURE = new mR("GENERATE_STRUCTURE", 17);
      KEEP_ALIVE = new mR("KEEP_ALIVE", 18);
      LOCK_DIFFICULTY = new mR("LOCK_DIFFICULTY", 19);
      PLAYER_POSITION = new mR("PLAYER_POSITION", 20);
      PLAYER_POSITION_AND_ROTATION = new mR("PLAYER_POSITION_AND_ROTATION", 21);
      PLAYER_ROTATION = new mR("PLAYER_ROTATION", 22);
      PLAYER_FLYING = new mR("PLAYER_FLYING", 23);
      VEHICLE_MOVE = new mR("VEHICLE_MOVE", 24);
      STEER_BOAT = new mR("STEER_BOAT", 25);
      PICK_ITEM = new mR("PICK_ITEM", 26);
      CRAFT_RECIPE_REQUEST = new mR("CRAFT_RECIPE_REQUEST", 27);
      PLAYER_ABILITIES = new mR("PLAYER_ABILITIES", 28);
      PLAYER_DIGGING = new mR("PLAYER_DIGGING", 29);
      ENTITY_ACTION = new mR("ENTITY_ACTION", 30);
      STEER_VEHICLE = new mR("STEER_VEHICLE", 31);
      PONG = new mR("PONG", 32);
      SET_RECIPE_BOOK_STATE = new mR("SET_RECIPE_BOOK_STATE", 33);
      SET_DISPLAYED_RECIPE = new mR("SET_DISPLAYED_RECIPE", 34);
      NAME_ITEM = new mR("NAME_ITEM", 35);
      RESOURCE_PACK_STATUS = new mR("RESOURCE_PACK_STATUS", 36);
      ADVANCEMENT_TAB = new mR("ADVANCEMENT_TAB", 37);
      SELECT_TRADE = new mR("SELECT_TRADE", 38);
      SET_BEACON_EFFECT = new mR("SET_BEACON_EFFECT", 39);
      HELD_ITEM_CHANGE = new mR("HELD_ITEM_CHANGE", 40);
      UPDATE_COMMAND_BLOCK = new mR("UPDATE_COMMAND_BLOCK", 41);
      UPDATE_COMMAND_BLOCK_MINECART = new mR("UPDATE_COMMAND_BLOCK_MINECART", 42);
      CREATIVE_INVENTORY_ACTION = new mR("CREATIVE_INVENTORY_ACTION", 43);
      UPDATE_JIGSAW_BLOCK = new mR("UPDATE_JIGSAW_BLOCK", 44);
      UPDATE_STRUCTURE_BLOCK = new mR("UPDATE_STRUCTURE_BLOCK", 45);
      UPDATE_SIGN = new mR("UPDATE_SIGN", 46);
      ANIMATION = new mR("ANIMATION", 47);
      SPECTATE = new mR("SPECTATE", 48);
      PLAYER_BLOCK_PLACEMENT = new mR("PLAYER_BLOCK_PLACEMENT", 49);
      USE_ITEM = new mR("USE_ITEM", 50);
   }
}
