package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum MV {
   CRAFTING_SHAPELESS,
   CRAFTING_SHAPED,
   CRAFTING_SPECIAL_ARMORDYE,
   CRAFTING_SPECIAL_BOOKCLONING,
   CRAFTING_SPECIAL_MAPCLONING,
   CRAFTING_SPECIAL_MAPEXTENDING,
   CRAFTING_SPECIAL_FIREWORK_ROCKET,
   CRAFTING_SPECIAL_FIREWORK_STAR,
   CRAFTING_SPECIAL_FIREWORK_STAR_FADE,
   CRAFTING_SPECIAL_REPAIRITEM,
   CRAFTING_SPECIAL_TIPPEDARROW,
   CRAFTING_SPECIAL_BANNERDUPLICATE,
   CRAFTING_SPECIAL_BANNERADDPATTERN,
   CRAFTING_SPECIAL_SHIELDDECORATION,
   CRAFTING_SPECIAL_SHULKERBOXCOLORING,
   CRAFTING_SPECIAL_SUSPICIOUSSTEW,
   SMELTING,
   BLASTING,
   SMOKING,
   CAMPFIRE_COOKING,
   STONECUTTING,
   SMITHING;

   private final aS<?> l;

   private MV(aS<?> var3) {
      this.l = var3;
   }

   // $FF: synthetic method
   private static MV[] D() {
      return new MV[]{CRAFTING_SHAPELESS, CRAFTING_SHAPED, CRAFTING_SPECIAL_ARMORDYE, CRAFTING_SPECIAL_BOOKCLONING, CRAFTING_SPECIAL_MAPCLONING, CRAFTING_SPECIAL_MAPEXTENDING, CRAFTING_SPECIAL_FIREWORK_ROCKET, CRAFTING_SPECIAL_FIREWORK_STAR, CRAFTING_SPECIAL_FIREWORK_STAR_FADE, CRAFTING_SPECIAL_REPAIRITEM, CRAFTING_SPECIAL_TIPPEDARROW, CRAFTING_SPECIAL_BANNERDUPLICATE, CRAFTING_SPECIAL_BANNERADDPATTERN, CRAFTING_SPECIAL_SHIELDDECORATION, CRAFTING_SPECIAL_SHULKERBOXCOLORING, CRAFTING_SPECIAL_SUSPICIOUSSTEW, SMELTING, BLASTING, SMOKING, CAMPFIRE_COOKING, STONECUTTING, SMITHING};
   }

   static {
      long var0 = kt.a(6406959360955257537L, -3382588123479270460L, MethodHandles.lookup().lookupClass()).a(6294081116335L) ^ 128536242472064L;
      CRAFTING_SHAPELESS = new MV("CRAFTING_SHAPELESS", 0, tK.r);
      CRAFTING_SHAPED = new MV("CRAFTING_SHAPED", 1, tK.M);
      CRAFTING_SPECIAL_ARMORDYE = new MV("CRAFTING_SPECIAL_ARMORDYE", 2, tK.E);
      CRAFTING_SPECIAL_BOOKCLONING = new MV("CRAFTING_SPECIAL_BOOKCLONING", 3, tK.y);
      CRAFTING_SPECIAL_MAPCLONING = new MV("CRAFTING_SPECIAL_MAPCLONING", 4, tK.o);
      CRAFTING_SPECIAL_MAPEXTENDING = new MV("CRAFTING_SPECIAL_MAPEXTENDING", 5, tK.P);
      CRAFTING_SPECIAL_FIREWORK_ROCKET = new MV("CRAFTING_SPECIAL_FIREWORK_ROCKET", 6, tK.h);
      CRAFTING_SPECIAL_FIREWORK_STAR = new MV("CRAFTING_SPECIAL_FIREWORK_STAR", 7, tK.i);
      CRAFTING_SPECIAL_FIREWORK_STAR_FADE = new MV("CRAFTING_SPECIAL_FIREWORK_STAR_FADE", 8, tK.j);
      CRAFTING_SPECIAL_REPAIRITEM = new MV("CRAFTING_SPECIAL_REPAIRITEM", 9, tK.B);
      CRAFTING_SPECIAL_TIPPEDARROW = new MV("CRAFTING_SPECIAL_TIPPEDARROW", 10, tK.s);
      CRAFTING_SPECIAL_BANNERDUPLICATE = new MV("CRAFTING_SPECIAL_BANNERDUPLICATE", 11, tK.W);
      CRAFTING_SPECIAL_BANNERADDPATTERN = new MV("CRAFTING_SPECIAL_BANNERADDPATTERN", 12, (aS)null);
      CRAFTING_SPECIAL_SHIELDDECORATION = new MV("CRAFTING_SPECIAL_SHIELDDECORATION", 13, tK.C);
      CRAFTING_SPECIAL_SHULKERBOXCOLORING = new MV("CRAFTING_SPECIAL_SHULKERBOXCOLORING", 14, tK.c);
      CRAFTING_SPECIAL_SUSPICIOUSSTEW = new MV("CRAFTING_SPECIAL_SUSPICIOUSSTEW", 15, tK.F);
      SMELTING = new MV("SMELTING", 16, tK.N);
      BLASTING = new MV("BLASTING", 17, tK.Z);
      SMOKING = new MV("SMOKING", 18, tK.b);
      CAMPFIRE_COOKING = new MV("CAMPFIRE_COOKING", 19, tK.a);
      STONECUTTING = new MV("STONECUTTING", 20, tK.p);
      SMITHING = new MV("SMITHING", 21, tK.k);
   }
}
