package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;
import java.util.Locale;

public enum N6 implements t {
   PERMISSION_DENIED,
   PERMISSION_DENIED_PARAMETER,
   ERROR_GENERIC_LOGGED,
   UNKNOWN_COMMAND,
   INVALID_SYNTAX,
   ERROR_PREFIX,
   ERROR_PERFORMING_COMMAND,
   INFO_MESSAGE,
   PLEASE_SPECIFY_ONE_OF,
   MUST_BE_A_NUMBER,
   MUST_BE_MIN_LENGTH,
   MUST_BE_MAX_LENGTH,
   PLEASE_SPECIFY_AT_LEAST,
   PLEASE_SPECIFY_AT_MOST,
   NOT_ALLOWED_ON_CONSOLE,
   COULD_NOT_FIND_PLAYER,
   NO_COMMAND_MATCHED_SEARCH,
   HELP_PAGE_INFORMATION,
   HELP_NO_RESULTS,
   HELP_HEADER,
   HELP_FORMAT,
   HELP_DETAILED_HEADER,
   HELP_DETAILED_COMMAND_FORMAT,
   HELP_DETAILED_PARAMETER_FORMAT,
   HELP_SEARCH_HEADER;

   private final Oh c;
   private static final long a = kt.a(-3394818116414707058L, -4374099481401975581L, MethodHandles.lookup().lookupClass()).a(21919805686642L);

   private N6() {
      long var3 = a ^ 1629184817104L;
      super(var1, var2);
      this.c = Oh.P("acf-core." + this.name().toLowerCase(Locale.ENGLISH));
   }

   public Oh n() {
      return this.c;
   }

   // $FF: synthetic method
   private static N6[] A() {
      return new N6[]{PERMISSION_DENIED, PERMISSION_DENIED_PARAMETER, ERROR_GENERIC_LOGGED, UNKNOWN_COMMAND, INVALID_SYNTAX, ERROR_PREFIX, ERROR_PERFORMING_COMMAND, INFO_MESSAGE, PLEASE_SPECIFY_ONE_OF, MUST_BE_A_NUMBER, MUST_BE_MIN_LENGTH, MUST_BE_MAX_LENGTH, PLEASE_SPECIFY_AT_LEAST, PLEASE_SPECIFY_AT_MOST, NOT_ALLOWED_ON_CONSOLE, COULD_NOT_FIND_PLAYER, NO_COMMAND_MATCHED_SEARCH, HELP_PAGE_INFORMATION, HELP_NO_RESULTS, HELP_HEADER, HELP_FORMAT, HELP_DETAILED_HEADER, HELP_DETAILED_COMMAND_FORMAT, HELP_DETAILED_PARAMETER_FORMAT, HELP_SEARCH_HEADER};
   }

   static {
      long var0 = a ^ 89358207395082L;
      PERMISSION_DENIED = new N6("PERMISSION_DENIED", 0);
      PERMISSION_DENIED_PARAMETER = new N6("PERMISSION_DENIED_PARAMETER", 1);
      ERROR_GENERIC_LOGGED = new N6("ERROR_GENERIC_LOGGED", 2);
      UNKNOWN_COMMAND = new N6("UNKNOWN_COMMAND", 3);
      INVALID_SYNTAX = new N6("INVALID_SYNTAX", 4);
      ERROR_PREFIX = new N6("ERROR_PREFIX", 5);
      ERROR_PERFORMING_COMMAND = new N6("ERROR_PERFORMING_COMMAND", 6);
      INFO_MESSAGE = new N6("INFO_MESSAGE", 7);
      PLEASE_SPECIFY_ONE_OF = new N6("PLEASE_SPECIFY_ONE_OF", 8);
      MUST_BE_A_NUMBER = new N6("MUST_BE_A_NUMBER", 9);
      MUST_BE_MIN_LENGTH = new N6("MUST_BE_MIN_LENGTH", 10);
      MUST_BE_MAX_LENGTH = new N6("MUST_BE_MAX_LENGTH", 11);
      PLEASE_SPECIFY_AT_LEAST = new N6("PLEASE_SPECIFY_AT_LEAST", 12);
      PLEASE_SPECIFY_AT_MOST = new N6("PLEASE_SPECIFY_AT_MOST", 13);
      NOT_ALLOWED_ON_CONSOLE = new N6("NOT_ALLOWED_ON_CONSOLE", 14);
      COULD_NOT_FIND_PLAYER = new N6("COULD_NOT_FIND_PLAYER", 15);
      NO_COMMAND_MATCHED_SEARCH = new N6("NO_COMMAND_MATCHED_SEARCH", 16);
      HELP_PAGE_INFORMATION = new N6("HELP_PAGE_INFORMATION", 17);
      HELP_NO_RESULTS = new N6("HELP_NO_RESULTS", 18);
      HELP_HEADER = new N6("HELP_HEADER", 19);
      HELP_FORMAT = new N6("HELP_FORMAT", 20);
      HELP_DETAILED_HEADER = new N6("HELP_DETAILED_HEADER", 21);
      HELP_DETAILED_COMMAND_FORMAT = new N6("HELP_DETAILED_COMMAND_FORMAT", 22);
      HELP_DETAILED_PARAMETER_FORMAT = new N6("HELP_DETAILED_PARAMETER_FORMAT", 23);
      HELP_SEARCH_HEADER = new N6("HELP_SEARCH_HEADER", 24);
   }
}
