package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum Na {
   TELEPORT_CONFIRM,
   QUERY_BLOCK_NBT,
   SELECT_BUNDLE_ITEM,
   SET_DIFFICULTY,
   CHAT_ACK,
   CHAT_COMMAND_UNSIGNED,
   CHAT_COMMAND,
   CHAT_MESSAGE,
   CHAT_SESSION_UPDATE,
   CHUNK_BATCH_ACK,
   CLIENT_STATUS,
   CLIENT_TICK_END,
   CLIENT_SETTINGS,
   TAB_COMPLETE,
   CONFIGURATION_ACK,
   CLICK_WINDOW_BUTTON,
   CLICK_WINDOW,
   CLOSE_WINDOW,
   SLOT_STATE_CHANGE,
   COOKIE_RESPONSE,
   PLUGIN_MESSAGE,
   DEBUG_SAMPLE_SUBSCRIPTION,
   EDIT_BOOK,
   QUERY_ENTITY_NBT,
   INTERACT_ENTITY,
   GENERATE_STRUCTURE,
   KEEP_ALIVE,
   LOCK_DIFFICULTY,
   PLAYER_POSITION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_ROTATION,
   PLAYER_FLYING,
   VEHICLE_MOVE,
   STEER_BOAT,
   PICK_ITEM_FROM_BLOCK,
   PICK_ITEM_FROM_ENTITY,
   DEBUG_PING,
   CRAFT_RECIPE_REQUEST,
   PLAYER_ABILITIES,
   PLAYER_DIGGING,
   ENTITY_ACTION,
   PLAYER_INPUT,
   PLAYER_LOADED,
   PONG,
   SET_RECIPE_BOOK_STATE,
   SET_DISPLAYED_RECIPE,
   NAME_ITEM,
   RESOURCE_PACK_STATUS,
   ADVANCEMENT_TAB,
   SELECT_TRADE,
   SET_BEACON_EFFECT,
   HELD_ITEM_CHANGE,
   UPDATE_COMMAND_BLOCK,
   UPDATE_COMMAND_BLOCK_MINECART,
   CREATIVE_INVENTORY_ACTION,
   UPDATE_JIGSAW_BLOCK,
   UPDATE_STRUCTURE_BLOCK,
   SET_TEST_BLOCK,
   UPDATE_SIGN,
   ANIMATION,
   SPECTATE,
   TEST_INSTANCE_BLOCK_ACTION,
   PLAYER_BLOCK_PLACEMENT,
   USE_ITEM;

   // $FF: synthetic method
   private static Na[] e() {
      return new Na[]{TELEPORT_CONFIRM, QUERY_BLOCK_NBT, SELECT_BUNDLE_ITEM, SET_DIFFICULTY, CHAT_ACK, CHAT_COMMAND_UNSIGNED, CHAT_COMMAND, CHAT_MESSAGE, CHAT_SESSION_UPDATE, CHUNK_BATCH_ACK, CLIENT_STATUS, CLIENT_TICK_END, CLIENT_SETTINGS, TAB_COMPLETE, CONFIGURATION_ACK, CLICK_WINDOW_BUTTON, CLICK_WINDOW, CLOSE_WINDOW, SLOT_STATE_CHANGE, COOKIE_RESPONSE, PLUGIN_MESSAGE, DEBUG_SAMPLE_SUBSCRIPTION, EDIT_BOOK, QUERY_ENTITY_NBT, INTERACT_ENTITY, GENERATE_STRUCTURE, KEEP_ALIVE, LOCK_DIFFICULTY, PLAYER_POSITION, PLAYER_POSITION_AND_ROTATION, PLAYER_ROTATION, PLAYER_FLYING, VEHICLE_MOVE, STEER_BOAT, PICK_ITEM_FROM_BLOCK, PICK_ITEM_FROM_ENTITY, DEBUG_PING, CRAFT_RECIPE_REQUEST, PLAYER_ABILITIES, PLAYER_DIGGING, ENTITY_ACTION, PLAYER_INPUT, PLAYER_LOADED, PONG, SET_RECIPE_BOOK_STATE, SET_DISPLAYED_RECIPE, NAME_ITEM, RESOURCE_PACK_STATUS, ADVANCEMENT_TAB, SELECT_TRADE, SET_BEACON_EFFECT, HELD_ITEM_CHANGE, UPDATE_COMMAND_BLOCK, UPDATE_COMMAND_BLOCK_MINECART, CREATIVE_INVENTORY_ACTION, UPDATE_JIGSAW_BLOCK, UPDATE_STRUCTURE_BLOCK, SET_TEST_BLOCK, UPDATE_SIGN, ANIMATION, SPECTATE, TEST_INSTANCE_BLOCK_ACTION, PLAYER_BLOCK_PLACEMENT, USE_ITEM};
   }

   static {
      long var0 = kt.a(2768097647545442884L, 4606412091335087790L, MethodHandles.lookup().lookupClass()).a(145736604283569L) ^ 132645533969548L;
      TELEPORT_CONFIRM = new Na("TELEPORT_CONFIRM", 0);
      QUERY_BLOCK_NBT = new Na("QUERY_BLOCK_NBT", 1);
      SELECT_BUNDLE_ITEM = new Na("SELECT_BUNDLE_ITEM", 2);
      SET_DIFFICULTY = new Na("SET_DIFFICULTY", 3);
      CHAT_ACK = new Na("CHAT_ACK", 4);
      CHAT_COMMAND_UNSIGNED = new Na("CHAT_COMMAND_UNSIGNED", 5);
      CHAT_COMMAND = new Na("CHAT_COMMAND", 6);
      CHAT_MESSAGE = new Na("CHAT_MESSAGE", 7);
      CHAT_SESSION_UPDATE = new Na("CHAT_SESSION_UPDATE", 8);
      CHUNK_BATCH_ACK = new Na("CHUNK_BATCH_ACK", 9);
      CLIENT_STATUS = new Na("CLIENT_STATUS", 10);
      CLIENT_TICK_END = new Na("CLIENT_TICK_END", 11);
      CLIENT_SETTINGS = new Na("CLIENT_SETTINGS", 12);
      TAB_COMPLETE = new Na("TAB_COMPLETE", 13);
      CONFIGURATION_ACK = new Na("CONFIGURATION_ACK", 14);
      CLICK_WINDOW_BUTTON = new Na("CLICK_WINDOW_BUTTON", 15);
      CLICK_WINDOW = new Na("CLICK_WINDOW", 16);
      CLOSE_WINDOW = new Na("CLOSE_WINDOW", 17);
      SLOT_STATE_CHANGE = new Na("SLOT_STATE_CHANGE", 18);
      COOKIE_RESPONSE = new Na("COOKIE_RESPONSE", 19);
      PLUGIN_MESSAGE = new Na("PLUGIN_MESSAGE", 20);
      DEBUG_SAMPLE_SUBSCRIPTION = new Na("DEBUG_SAMPLE_SUBSCRIPTION", 21);
      EDIT_BOOK = new Na("EDIT_BOOK", 22);
      QUERY_ENTITY_NBT = new Na("QUERY_ENTITY_NBT", 23);
      INTERACT_ENTITY = new Na("INTERACT_ENTITY", 24);
      GENERATE_STRUCTURE = new Na("GENERATE_STRUCTURE", 25);
      KEEP_ALIVE = new Na("KEEP_ALIVE", 26);
      LOCK_DIFFICULTY = new Na("LOCK_DIFFICULTY", 27);
      PLAYER_POSITION = new Na("PLAYER_POSITION", 28);
      PLAYER_POSITION_AND_ROTATION = new Na("PLAYER_POSITION_AND_ROTATION", 29);
      PLAYER_ROTATION = new Na("PLAYER_ROTATION", 30);
      PLAYER_FLYING = new Na("PLAYER_FLYING", 31);
      VEHICLE_MOVE = new Na("VEHICLE_MOVE", 32);
      STEER_BOAT = new Na("STEER_BOAT", 33);
      PICK_ITEM_FROM_BLOCK = new Na("PICK_ITEM_FROM_BLOCK", 34);
      PICK_ITEM_FROM_ENTITY = new Na("PICK_ITEM_FROM_ENTITY", 35);
      DEBUG_PING = new Na("DEBUG_PING", 36);
      CRAFT_RECIPE_REQUEST = new Na("CRAFT_RECIPE_REQUEST", 37);
      PLAYER_ABILITIES = new Na("PLAYER_ABILITIES", 38);
      PLAYER_DIGGING = new Na("PLAYER_DIGGING", 39);
      ENTITY_ACTION = new Na("ENTITY_ACTION", 40);
      PLAYER_INPUT = new Na("PLAYER_INPUT", 41);
      PLAYER_LOADED = new Na("PLAYER_LOADED", 42);
      PONG = new Na("PONG", 43);
      SET_RECIPE_BOOK_STATE = new Na("SET_RECIPE_BOOK_STATE", 44);
      SET_DISPLAYED_RECIPE = new Na("SET_DISPLAYED_RECIPE", 45);
      NAME_ITEM = new Na("NAME_ITEM", 46);
      RESOURCE_PACK_STATUS = new Na("RESOURCE_PACK_STATUS", 47);
      ADVANCEMENT_TAB = new Na("ADVANCEMENT_TAB", 48);
      SELECT_TRADE = new Na("SELECT_TRADE", 49);
      SET_BEACON_EFFECT = new Na("SET_BEACON_EFFECT", 50);
      HELD_ITEM_CHANGE = new Na("HELD_ITEM_CHANGE", 51);
      UPDATE_COMMAND_BLOCK = new Na("UPDATE_COMMAND_BLOCK", 52);
      UPDATE_COMMAND_BLOCK_MINECART = new Na("UPDATE_COMMAND_BLOCK_MINECART", 53);
      CREATIVE_INVENTORY_ACTION = new Na("CREATIVE_INVENTORY_ACTION", 54);
      UPDATE_JIGSAW_BLOCK = new Na("UPDATE_JIGSAW_BLOCK", 55);
      UPDATE_STRUCTURE_BLOCK = new Na("UPDATE_STRUCTURE_BLOCK", 56);
      SET_TEST_BLOCK = new Na("SET_TEST_BLOCK", 57);
      UPDATE_SIGN = new Na("UPDATE_SIGN", 58);
      ANIMATION = new Na("ANIMATION", 59);
      SPECTATE = new Na("SPECTATE", 60);
      TEST_INSTANCE_BLOCK_ACTION = new Na("TEST_INSTANCE_BLOCK_ACTION", 61);
      PLAYER_BLOCK_PLACEMENT = new Na("PLAYER_BLOCK_PLACEMENT", 62);
      USE_ITEM = new Na("USE_ITEM", 63);
   }
}
