package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum ox {
   SPAWN_ENTITY,
   SPAWN_EXPERIENCE_ORB,
   SPAWN_LIVING_ENTITY,
   SPAWN_PAINTING,
   SPAWN_PLAYER,
   SCULK_VIBRATION_SIGNAL,
   ENTITY_ANIMATION,
   STATISTICS,
   ACKNOWLEDGE_PLAYER_DIGGING,
   BLOCK_BREAK_ANIMATION,
   BLOCK_ENTITY_DATA,
   BLOCK_ACTION,
   BLOCK_CHANGE,
   BOSS_BAR,
   SERVER_DIFFICULTY,
   CHAT_MESSAGE,
   CLEAR_TITLES,
   TAB_COMPLETE,
   DECLARE_COMMANDS,
   CLOSE_WINDOW,
   WINDOW_ITEMS,
   WINDOW_PROPERTY,
   SET_SLOT,
   SET_COOLDOWN,
   PLUGIN_MESSAGE,
   NAMED_SOUND_EFFECT,
   DISCONNECT,
   ENTITY_STATUS,
   EXPLOSION,
   UNLOAD_CHUNK,
   CHANGE_GAME_STATE,
   OPEN_HORSE_WINDOW,
   INITIALIZE_WORLD_BORDER,
   KEEP_ALIVE,
   CHUNK_DATA,
   EFFECT,
   PARTICLE,
   UPDATE_LIGHT,
   JOIN_GAME,
   MAP_DATA,
   MERCHANT_OFFERS,
   ENTITY_RELATIVE_MOVE,
   ENTITY_RELATIVE_MOVE_AND_ROTATION,
   ENTITY_ROTATION,
   VEHICLE_MOVE,
   OPEN_BOOK,
   OPEN_WINDOW,
   OPEN_SIGN_EDITOR,
   PING,
   CRAFT_RECIPE_RESPONSE,
   PLAYER_ABILITIES,
   END_COMBAT_EVENT,
   ENTER_COMBAT_EVENT,
   DEATH_COMBAT_EVENT,
   PLAYER_INFO,
   FACE_PLAYER,
   PLAYER_POSITION_AND_LOOK,
   UNLOCK_RECIPES,
   DESTROY_ENTITIES,
   REMOVE_ENTITY_EFFECT,
   RESOURCE_PACK_SEND,
   RESPAWN,
   ENTITY_HEAD_LOOK,
   MULTI_BLOCK_CHANGE,
   SELECT_ADVANCEMENTS_TAB,
   ACTION_BAR,
   WORLD_BORDER_CENTER,
   WORLD_BORDER_LERP_SIZE,
   WORLD_BORDER_SIZE,
   WORLD_BORDER_WARNING_DELAY,
   WORLD_BORDER_WARNING_REACH,
   CAMERA,
   HELD_ITEM_CHANGE,
   UPDATE_VIEW_POSITION,
   UPDATE_VIEW_DISTANCE,
   SPAWN_POSITION,
   DISPLAY_SCOREBOARD,
   ENTITY_METADATA,
   ATTACH_ENTITY,
   ENTITY_VELOCITY,
   ENTITY_EQUIPMENT,
   SET_EXPERIENCE,
   UPDATE_HEALTH,
   SCOREBOARD_OBJECTIVE,
   SET_PASSENGERS,
   TEAMS,
   UPDATE_SCORE,
   SET_TITLE_SUBTITLE,
   TIME_UPDATE,
   SET_TITLE_TEXT,
   SET_TITLE_TIMES,
   ENTITY_SOUND_EFFECT,
   SOUND_EFFECT,
   STOP_SOUND,
   PLAYER_LIST_HEADER_AND_FOOTER,
   NBT_QUERY_RESPONSE,
   COLLECT_ITEM,
   ENTITY_TELEPORT,
   UPDATE_ADVANCEMENTS,
   UPDATE_ATTRIBUTES,
   ENTITY_EFFECT,
   DECLARE_RECIPES,
   TAGS;

   // $FF: synthetic method
   private static ox[] M() {
      return new ox[]{SPAWN_ENTITY, SPAWN_EXPERIENCE_ORB, SPAWN_LIVING_ENTITY, SPAWN_PAINTING, SPAWN_PLAYER, SCULK_VIBRATION_SIGNAL, ENTITY_ANIMATION, STATISTICS, ACKNOWLEDGE_PLAYER_DIGGING, BLOCK_BREAK_ANIMATION, BLOCK_ENTITY_DATA, BLOCK_ACTION, BLOCK_CHANGE, BOSS_BAR, SERVER_DIFFICULTY, CHAT_MESSAGE, CLEAR_TITLES, TAB_COMPLETE, DECLARE_COMMANDS, CLOSE_WINDOW, WINDOW_ITEMS, WINDOW_PROPERTY, SET_SLOT, SET_COOLDOWN, PLUGIN_MESSAGE, NAMED_SOUND_EFFECT, DISCONNECT, ENTITY_STATUS, EXPLOSION, UNLOAD_CHUNK, CHANGE_GAME_STATE, OPEN_HORSE_WINDOW, INITIALIZE_WORLD_BORDER, KEEP_ALIVE, CHUNK_DATA, EFFECT, PARTICLE, UPDATE_LIGHT, JOIN_GAME, MAP_DATA, MERCHANT_OFFERS, ENTITY_RELATIVE_MOVE, ENTITY_RELATIVE_MOVE_AND_ROTATION, ENTITY_ROTATION, VEHICLE_MOVE, OPEN_BOOK, OPEN_WINDOW, OPEN_SIGN_EDITOR, PING, CRAFT_RECIPE_RESPONSE, PLAYER_ABILITIES, END_COMBAT_EVENT, ENTER_COMBAT_EVENT, DEATH_COMBAT_EVENT, PLAYER_INFO, FACE_PLAYER, PLAYER_POSITION_AND_LOOK, UNLOCK_RECIPES, DESTROY_ENTITIES, REMOVE_ENTITY_EFFECT, RESOURCE_PACK_SEND, RESPAWN, ENTITY_HEAD_LOOK, MULTI_BLOCK_CHANGE, SELECT_ADVANCEMENTS_TAB, ACTION_BAR, WORLD_BORDER_CENTER, WORLD_BORDER_LERP_SIZE, WORLD_BORDER_SIZE, WORLD_BORDER_WARNING_DELAY, WORLD_BORDER_WARNING_REACH, CAMERA, HELD_ITEM_CHANGE, UPDATE_VIEW_POSITION, UPDATE_VIEW_DISTANCE, SPAWN_POSITION, DISPLAY_SCOREBOARD, ENTITY_METADATA, ATTACH_ENTITY, ENTITY_VELOCITY, ENTITY_EQUIPMENT, SET_EXPERIENCE, UPDATE_HEALTH, SCOREBOARD_OBJECTIVE, SET_PASSENGERS, TEAMS, UPDATE_SCORE, SET_TITLE_SUBTITLE, TIME_UPDATE, SET_TITLE_TEXT, SET_TITLE_TIMES, ENTITY_SOUND_EFFECT, SOUND_EFFECT, STOP_SOUND, PLAYER_LIST_HEADER_AND_FOOTER, NBT_QUERY_RESPONSE, COLLECT_ITEM, ENTITY_TELEPORT, UPDATE_ADVANCEMENTS, UPDATE_ATTRIBUTES, ENTITY_EFFECT, DECLARE_RECIPES, TAGS};
   }

   static {
      long var0 = kt.a(-1867080593086543134L, 1652733643746432424L, MethodHandles.lookup().lookupClass()).a(110967065622212L) ^ 39191666836093L;
      SPAWN_ENTITY = new ox("SPAWN_ENTITY", 0);
      SPAWN_EXPERIENCE_ORB = new ox("SPAWN_EXPERIENCE_ORB", 1);
      SPAWN_LIVING_ENTITY = new ox("SPAWN_LIVING_ENTITY", 2);
      SPAWN_PAINTING = new ox("SPAWN_PAINTING", 3);
      SPAWN_PLAYER = new ox("SPAWN_PLAYER", 4);
      SCULK_VIBRATION_SIGNAL = new ox("SCULK_VIBRATION_SIGNAL", 5);
      ENTITY_ANIMATION = new ox("ENTITY_ANIMATION", 6);
      STATISTICS = new ox("STATISTICS", 7);
      ACKNOWLEDGE_PLAYER_DIGGING = new ox("ACKNOWLEDGE_PLAYER_DIGGING", 8);
      BLOCK_BREAK_ANIMATION = new ox("BLOCK_BREAK_ANIMATION", 9);
      BLOCK_ENTITY_DATA = new ox("BLOCK_ENTITY_DATA", 10);
      BLOCK_ACTION = new ox("BLOCK_ACTION", 11);
      BLOCK_CHANGE = new ox("BLOCK_CHANGE", 12);
      BOSS_BAR = new ox("BOSS_BAR", 13);
      SERVER_DIFFICULTY = new ox("SERVER_DIFFICULTY", 14);
      CHAT_MESSAGE = new ox("CHAT_MESSAGE", 15);
      CLEAR_TITLES = new ox("CLEAR_TITLES", 16);
      TAB_COMPLETE = new ox("TAB_COMPLETE", 17);
      DECLARE_COMMANDS = new ox("DECLARE_COMMANDS", 18);
      CLOSE_WINDOW = new ox("CLOSE_WINDOW", 19);
      WINDOW_ITEMS = new ox("WINDOW_ITEMS", 20);
      WINDOW_PROPERTY = new ox("WINDOW_PROPERTY", 21);
      SET_SLOT = new ox("SET_SLOT", 22);
      SET_COOLDOWN = new ox("SET_COOLDOWN", 23);
      PLUGIN_MESSAGE = new ox("PLUGIN_MESSAGE", 24);
      NAMED_SOUND_EFFECT = new ox("NAMED_SOUND_EFFECT", 25);
      DISCONNECT = new ox("DISCONNECT", 26);
      ENTITY_STATUS = new ox("ENTITY_STATUS", 27);
      EXPLOSION = new ox("EXPLOSION", 28);
      UNLOAD_CHUNK = new ox("UNLOAD_CHUNK", 29);
      CHANGE_GAME_STATE = new ox("CHANGE_GAME_STATE", 30);
      OPEN_HORSE_WINDOW = new ox("OPEN_HORSE_WINDOW", 31);
      INITIALIZE_WORLD_BORDER = new ox("INITIALIZE_WORLD_BORDER", 32);
      KEEP_ALIVE = new ox("KEEP_ALIVE", 33);
      CHUNK_DATA = new ox("CHUNK_DATA", 34);
      EFFECT = new ox("EFFECT", 35);
      PARTICLE = new ox("PARTICLE", 36);
      UPDATE_LIGHT = new ox("UPDATE_LIGHT", 37);
      JOIN_GAME = new ox("JOIN_GAME", 38);
      MAP_DATA = new ox("MAP_DATA", 39);
      MERCHANT_OFFERS = new ox("MERCHANT_OFFERS", 40);
      ENTITY_RELATIVE_MOVE = new ox("ENTITY_RELATIVE_MOVE", 41);
      ENTITY_RELATIVE_MOVE_AND_ROTATION = new ox("ENTITY_RELATIVE_MOVE_AND_ROTATION", 42);
      ENTITY_ROTATION = new ox("ENTITY_ROTATION", 43);
      VEHICLE_MOVE = new ox("VEHICLE_MOVE", 44);
      OPEN_BOOK = new ox("OPEN_BOOK", 45);
      OPEN_WINDOW = new ox("OPEN_WINDOW", 46);
      OPEN_SIGN_EDITOR = new ox("OPEN_SIGN_EDITOR", 47);
      PING = new ox("PING", 48);
      CRAFT_RECIPE_RESPONSE = new ox("CRAFT_RECIPE_RESPONSE", 49);
      PLAYER_ABILITIES = new ox("PLAYER_ABILITIES", 50);
      END_COMBAT_EVENT = new ox("END_COMBAT_EVENT", 51);
      ENTER_COMBAT_EVENT = new ox("ENTER_COMBAT_EVENT", 52);
      DEATH_COMBAT_EVENT = new ox("DEATH_COMBAT_EVENT", 53);
      PLAYER_INFO = new ox("PLAYER_INFO", 54);
      FACE_PLAYER = new ox("FACE_PLAYER", 55);
      PLAYER_POSITION_AND_LOOK = new ox("PLAYER_POSITION_AND_LOOK", 56);
      UNLOCK_RECIPES = new ox("UNLOCK_RECIPES", 57);
      DESTROY_ENTITIES = new ox("DESTROY_ENTITIES", 58);
      REMOVE_ENTITY_EFFECT = new ox("REMOVE_ENTITY_EFFECT", 59);
      RESOURCE_PACK_SEND = new ox("RESOURCE_PACK_SEND", 60);
      RESPAWN = new ox("RESPAWN", 61);
      ENTITY_HEAD_LOOK = new ox("ENTITY_HEAD_LOOK", 62);
      MULTI_BLOCK_CHANGE = new ox("MULTI_BLOCK_CHANGE", 63);
      SELECT_ADVANCEMENTS_TAB = new ox("SELECT_ADVANCEMENTS_TAB", 64);
      ACTION_BAR = new ox("ACTION_BAR", 65);
      WORLD_BORDER_CENTER = new ox("WORLD_BORDER_CENTER", 66);
      WORLD_BORDER_LERP_SIZE = new ox("WORLD_BORDER_LERP_SIZE", 67);
      WORLD_BORDER_SIZE = new ox("WORLD_BORDER_SIZE", 68);
      WORLD_BORDER_WARNING_DELAY = new ox("WORLD_BORDER_WARNING_DELAY", 69);
      WORLD_BORDER_WARNING_REACH = new ox("WORLD_BORDER_WARNING_REACH", 70);
      CAMERA = new ox("CAMERA", 71);
      HELD_ITEM_CHANGE = new ox("HELD_ITEM_CHANGE", 72);
      UPDATE_VIEW_POSITION = new ox("UPDATE_VIEW_POSITION", 73);
      UPDATE_VIEW_DISTANCE = new ox("UPDATE_VIEW_DISTANCE", 74);
      SPAWN_POSITION = new ox("SPAWN_POSITION", 75);
      DISPLAY_SCOREBOARD = new ox("DISPLAY_SCOREBOARD", 76);
      ENTITY_METADATA = new ox("ENTITY_METADATA", 77);
      ATTACH_ENTITY = new ox("ATTACH_ENTITY", 78);
      ENTITY_VELOCITY = new ox("ENTITY_VELOCITY", 79);
      ENTITY_EQUIPMENT = new ox("ENTITY_EQUIPMENT", 80);
      SET_EXPERIENCE = new ox("SET_EXPERIENCE", 81);
      UPDATE_HEALTH = new ox("UPDATE_HEALTH", 82);
      SCOREBOARD_OBJECTIVE = new ox("SCOREBOARD_OBJECTIVE", 83);
      SET_PASSENGERS = new ox("SET_PASSENGERS", 84);
      TEAMS = new ox("TEAMS", 85);
      UPDATE_SCORE = new ox("UPDATE_SCORE", 86);
      SET_TITLE_SUBTITLE = new ox("SET_TITLE_SUBTITLE", 87);
      TIME_UPDATE = new ox("TIME_UPDATE", 88);
      SET_TITLE_TEXT = new ox("SET_TITLE_TEXT", 89);
      SET_TITLE_TIMES = new ox("SET_TITLE_TIMES", 90);
      ENTITY_SOUND_EFFECT = new ox("ENTITY_SOUND_EFFECT", 91);
      SOUND_EFFECT = new ox("SOUND_EFFECT", 92);
      STOP_SOUND = new ox("STOP_SOUND", 93);
      PLAYER_LIST_HEADER_AND_FOOTER = new ox("PLAYER_LIST_HEADER_AND_FOOTER", 94);
      NBT_QUERY_RESPONSE = new ox("NBT_QUERY_RESPONSE", 95);
      COLLECT_ITEM = new ox("COLLECT_ITEM", 96);
      ENTITY_TELEPORT = new ox("ENTITY_TELEPORT", 97);
      UPDATE_ADVANCEMENTS = new ox("UPDATE_ADVANCEMENTS", 98);
      UPDATE_ATTRIBUTES = new ox("UPDATE_ATTRIBUTES", 99);
      ENTITY_EFFECT = new ox("ENTITY_EFFECT", 100);
      DECLARE_RECIPES = new ox("DECLARE_RECIPES", 101);
      TAGS = new ox("TAGS", 102);
   }
}
