package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum RD {
   SPAWN_ENTITY,
   SPAWN_EXPERIENCE_ORB,
   SPAWN_LIVING_ENTITY,
   SPAWN_PAINTING,
   SPAWN_PLAYER,
   ENTITY_ANIMATION,
   STATISTICS,
   ACKNOWLEDGE_PLAYER_DIGGING,
   BLOCK_BREAK_ANIMATION,
   BLOCK_ENTITY_DATA,
   BLOCK_ACTION,
   BLOCK_CHANGE,
   BOSS_BAR,
   SERVER_DIFFICULTY,
   CHAT_MESSAGE,
   MULTI_BLOCK_CHANGE,
   TAB_COMPLETE,
   DECLARE_COMMANDS,
   WINDOW_CONFIRMATION,
   CLOSE_WINDOW,
   WINDOW_ITEMS,
   WINDOW_PROPERTY,
   SET_SLOT,
   SET_COOLDOWN,
   PLUGIN_MESSAGE,
   NAMED_SOUND_EFFECT,
   DISCONNECT,
   ENTITY_STATUS,
   EXPLOSION,
   UNLOAD_CHUNK,
   CHANGE_GAME_STATE,
   OPEN_HORSE_WINDOW,
   KEEP_ALIVE,
   CHUNK_DATA,
   EFFECT,
   PARTICLE,
   UPDATE_LIGHT,
   JOIN_GAME,
   MAP_DATA,
   MERCHANT_OFFERS,
   ENTITY_RELATIVE_MOVE,
   ENTITY_RELATIVE_MOVE_AND_ROTATION,
   ENTITY_ROTATION,
   ENTITY_MOVEMENT,
   VEHICLE_MOVE,
   OPEN_BOOK,
   OPEN_WINDOW,
   OPEN_SIGN_EDITOR,
   CRAFT_RECIPE_RESPONSE,
   PLAYER_ABILITIES,
   COMBAT_EVENT,
   PLAYER_INFO,
   FACE_PLAYER,
   PLAYER_POSITION_AND_LOOK,
   UNLOCK_RECIPES,
   DESTROY_ENTITIES,
   REMOVE_ENTITY_EFFECT,
   RESOURCE_PACK_SEND,
   RESPAWN,
   ENTITY_HEAD_LOOK,
   SELECT_ADVANCEMENTS_TAB,
   WORLD_BORDER,
   CAMERA,
   HELD_ITEM_CHANGE,
   UPDATE_VIEW_POSITION,
   UPDATE_VIEW_DISTANCE,
   DISPLAY_SCOREBOARD,
   ENTITY_METADATA,
   ATTACH_ENTITY,
   ENTITY_VELOCITY,
   ENTITY_EQUIPMENT,
   SET_EXPERIENCE,
   UPDATE_HEALTH,
   SCOREBOARD_OBJECTIVE,
   SET_PASSENGERS,
   TEAMS,
   UPDATE_SCORE,
   SPAWN_POSITION,
   TIME_UPDATE,
   TITLE,
   ENTITY_SOUND_EFFECT,
   SOUND_EFFECT,
   STOP_SOUND,
   PLAYER_LIST_HEADER_AND_FOOTER,
   NBT_QUERY_RESPONSE,
   COLLECT_ITEM,
   ENTITY_TELEPORT,
   UPDATE_ADVANCEMENTS,
   UPDATE_ATTRIBUTES,
   ENTITY_EFFECT,
   DECLARE_RECIPES,
   TAGS;

   // $FF: synthetic method
   private static RD[] Q() {
      return new RD[]{SPAWN_ENTITY, SPAWN_EXPERIENCE_ORB, SPAWN_LIVING_ENTITY, SPAWN_PAINTING, SPAWN_PLAYER, ENTITY_ANIMATION, STATISTICS, ACKNOWLEDGE_PLAYER_DIGGING, BLOCK_BREAK_ANIMATION, BLOCK_ENTITY_DATA, BLOCK_ACTION, BLOCK_CHANGE, BOSS_BAR, SERVER_DIFFICULTY, CHAT_MESSAGE, MULTI_BLOCK_CHANGE, TAB_COMPLETE, DECLARE_COMMANDS, WINDOW_CONFIRMATION, CLOSE_WINDOW, WINDOW_ITEMS, WINDOW_PROPERTY, SET_SLOT, SET_COOLDOWN, PLUGIN_MESSAGE, NAMED_SOUND_EFFECT, DISCONNECT, ENTITY_STATUS, EXPLOSION, UNLOAD_CHUNK, CHANGE_GAME_STATE, OPEN_HORSE_WINDOW, KEEP_ALIVE, CHUNK_DATA, EFFECT, PARTICLE, UPDATE_LIGHT, JOIN_GAME, MAP_DATA, MERCHANT_OFFERS, ENTITY_RELATIVE_MOVE, ENTITY_RELATIVE_MOVE_AND_ROTATION, ENTITY_ROTATION, ENTITY_MOVEMENT, VEHICLE_MOVE, OPEN_BOOK, OPEN_WINDOW, OPEN_SIGN_EDITOR, CRAFT_RECIPE_RESPONSE, PLAYER_ABILITIES, COMBAT_EVENT, PLAYER_INFO, FACE_PLAYER, PLAYER_POSITION_AND_LOOK, UNLOCK_RECIPES, DESTROY_ENTITIES, REMOVE_ENTITY_EFFECT, RESOURCE_PACK_SEND, RESPAWN, ENTITY_HEAD_LOOK, SELECT_ADVANCEMENTS_TAB, WORLD_BORDER, CAMERA, HELD_ITEM_CHANGE, UPDATE_VIEW_POSITION, UPDATE_VIEW_DISTANCE, DISPLAY_SCOREBOARD, ENTITY_METADATA, ATTACH_ENTITY, ENTITY_VELOCITY, ENTITY_EQUIPMENT, SET_EXPERIENCE, UPDATE_HEALTH, SCOREBOARD_OBJECTIVE, SET_PASSENGERS, TEAMS, UPDATE_SCORE, SPAWN_POSITION, TIME_UPDATE, TITLE, ENTITY_SOUND_EFFECT, SOUND_EFFECT, STOP_SOUND, PLAYER_LIST_HEADER_AND_FOOTER, NBT_QUERY_RESPONSE, COLLECT_ITEM, ENTITY_TELEPORT, UPDATE_ADVANCEMENTS, UPDATE_ATTRIBUTES, ENTITY_EFFECT, DECLARE_RECIPES, TAGS};
   }

   static {
      long var0 = kt.a(4487762993838184452L, 8431347396528129604L, MethodHandles.lookup().lookupClass()).a(128570897840258L) ^ 116392674561192L;
      SPAWN_ENTITY = new RD("SPAWN_ENTITY", 0);
      SPAWN_EXPERIENCE_ORB = new RD("SPAWN_EXPERIENCE_ORB", 1);
      SPAWN_LIVING_ENTITY = new RD("SPAWN_LIVING_ENTITY", 2);
      SPAWN_PAINTING = new RD("SPAWN_PAINTING", 3);
      SPAWN_PLAYER = new RD("SPAWN_PLAYER", 4);
      ENTITY_ANIMATION = new RD("ENTITY_ANIMATION", 5);
      STATISTICS = new RD("STATISTICS", 6);
      ACKNOWLEDGE_PLAYER_DIGGING = new RD("ACKNOWLEDGE_PLAYER_DIGGING", 7);
      BLOCK_BREAK_ANIMATION = new RD("BLOCK_BREAK_ANIMATION", 8);
      BLOCK_ENTITY_DATA = new RD("BLOCK_ENTITY_DATA", 9);
      BLOCK_ACTION = new RD("BLOCK_ACTION", 10);
      BLOCK_CHANGE = new RD("BLOCK_CHANGE", 11);
      BOSS_BAR = new RD("BOSS_BAR", 12);
      SERVER_DIFFICULTY = new RD("SERVER_DIFFICULTY", 13);
      CHAT_MESSAGE = new RD("CHAT_MESSAGE", 14);
      MULTI_BLOCK_CHANGE = new RD("MULTI_BLOCK_CHANGE", 15);
      TAB_COMPLETE = new RD("TAB_COMPLETE", 16);
      DECLARE_COMMANDS = new RD("DECLARE_COMMANDS", 17);
      WINDOW_CONFIRMATION = new RD("WINDOW_CONFIRMATION", 18);
      CLOSE_WINDOW = new RD("CLOSE_WINDOW", 19);
      WINDOW_ITEMS = new RD("WINDOW_ITEMS", 20);
      WINDOW_PROPERTY = new RD("WINDOW_PROPERTY", 21);
      SET_SLOT = new RD("SET_SLOT", 22);
      SET_COOLDOWN = new RD("SET_COOLDOWN", 23);
      PLUGIN_MESSAGE = new RD("PLUGIN_MESSAGE", 24);
      NAMED_SOUND_EFFECT = new RD("NAMED_SOUND_EFFECT", 25);
      DISCONNECT = new RD("DISCONNECT", 26);
      ENTITY_STATUS = new RD("ENTITY_STATUS", 27);
      EXPLOSION = new RD("EXPLOSION", 28);
      UNLOAD_CHUNK = new RD("UNLOAD_CHUNK", 29);
      CHANGE_GAME_STATE = new RD("CHANGE_GAME_STATE", 30);
      OPEN_HORSE_WINDOW = new RD("OPEN_HORSE_WINDOW", 31);
      KEEP_ALIVE = new RD("KEEP_ALIVE", 32);
      CHUNK_DATA = new RD("CHUNK_DATA", 33);
      EFFECT = new RD("EFFECT", 34);
      PARTICLE = new RD("PARTICLE", 35);
      UPDATE_LIGHT = new RD("UPDATE_LIGHT", 36);
      JOIN_GAME = new RD("JOIN_GAME", 37);
      MAP_DATA = new RD("MAP_DATA", 38);
      MERCHANT_OFFERS = new RD("MERCHANT_OFFERS", 39);
      ENTITY_RELATIVE_MOVE = new RD("ENTITY_RELATIVE_MOVE", 40);
      ENTITY_RELATIVE_MOVE_AND_ROTATION = new RD("ENTITY_RELATIVE_MOVE_AND_ROTATION", 41);
      ENTITY_ROTATION = new RD("ENTITY_ROTATION", 42);
      ENTITY_MOVEMENT = new RD("ENTITY_MOVEMENT", 43);
      VEHICLE_MOVE = new RD("VEHICLE_MOVE", 44);
      OPEN_BOOK = new RD("OPEN_BOOK", 45);
      OPEN_WINDOW = new RD("OPEN_WINDOW", 46);
      OPEN_SIGN_EDITOR = new RD("OPEN_SIGN_EDITOR", 47);
      CRAFT_RECIPE_RESPONSE = new RD("CRAFT_RECIPE_RESPONSE", 48);
      PLAYER_ABILITIES = new RD("PLAYER_ABILITIES", 49);
      COMBAT_EVENT = new RD("COMBAT_EVENT", 50);
      PLAYER_INFO = new RD("PLAYER_INFO", 51);
      FACE_PLAYER = new RD("FACE_PLAYER", 52);
      PLAYER_POSITION_AND_LOOK = new RD("PLAYER_POSITION_AND_LOOK", 53);
      UNLOCK_RECIPES = new RD("UNLOCK_RECIPES", 54);
      DESTROY_ENTITIES = new RD("DESTROY_ENTITIES", 55);
      REMOVE_ENTITY_EFFECT = new RD("REMOVE_ENTITY_EFFECT", 56);
      RESOURCE_PACK_SEND = new RD("RESOURCE_PACK_SEND", 57);
      RESPAWN = new RD("RESPAWN", 58);
      ENTITY_HEAD_LOOK = new RD("ENTITY_HEAD_LOOK", 59);
      SELECT_ADVANCEMENTS_TAB = new RD("SELECT_ADVANCEMENTS_TAB", 60);
      WORLD_BORDER = new RD("WORLD_BORDER", 61);
      CAMERA = new RD("CAMERA", 62);
      HELD_ITEM_CHANGE = new RD("HELD_ITEM_CHANGE", 63);
      UPDATE_VIEW_POSITION = new RD("UPDATE_VIEW_POSITION", 64);
      UPDATE_VIEW_DISTANCE = new RD("UPDATE_VIEW_DISTANCE", 65);
      DISPLAY_SCOREBOARD = new RD("DISPLAY_SCOREBOARD", 66);
      ENTITY_METADATA = new RD("ENTITY_METADATA", 67);
      ATTACH_ENTITY = new RD("ATTACH_ENTITY", 68);
      ENTITY_VELOCITY = new RD("ENTITY_VELOCITY", 69);
      ENTITY_EQUIPMENT = new RD("ENTITY_EQUIPMENT", 70);
      SET_EXPERIENCE = new RD("SET_EXPERIENCE", 71);
      UPDATE_HEALTH = new RD("UPDATE_HEALTH", 72);
      SCOREBOARD_OBJECTIVE = new RD("SCOREBOARD_OBJECTIVE", 73);
      SET_PASSENGERS = new RD("SET_PASSENGERS", 74);
      TEAMS = new RD("TEAMS", 75);
      UPDATE_SCORE = new RD("UPDATE_SCORE", 76);
      SPAWN_POSITION = new RD("SPAWN_POSITION", 77);
      TIME_UPDATE = new RD("TIME_UPDATE", 78);
      TITLE = new RD("TITLE", 79);
      ENTITY_SOUND_EFFECT = new RD("ENTITY_SOUND_EFFECT", 80);
      SOUND_EFFECT = new RD("SOUND_EFFECT", 81);
      STOP_SOUND = new RD("STOP_SOUND", 82);
      PLAYER_LIST_HEADER_AND_FOOTER = new RD("PLAYER_LIST_HEADER_AND_FOOTER", 83);
      NBT_QUERY_RESPONSE = new RD("NBT_QUERY_RESPONSE", 84);
      COLLECT_ITEM = new RD("COLLECT_ITEM", 85);
      ENTITY_TELEPORT = new RD("ENTITY_TELEPORT", 86);
      UPDATE_ADVANCEMENTS = new RD("UPDATE_ADVANCEMENTS", 87);
      UPDATE_ATTRIBUTES = new RD("UPDATE_ATTRIBUTES", 88);
      ENTITY_EFFECT = new RD("ENTITY_EFFECT", 89);
      DECLARE_RECIPES = new RD("DECLARE_RECIPES", 90);
      TAGS = new RD("TAGS", 91);
   }
}
