package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum RV {
   BUNDLE,
   SPAWN_ENTITY,
   ENTITY_ANIMATION,
   STATISTICS,
   ACKNOWLEDGE_BLOCK_CHANGES,
   BLOCK_BREAK_ANIMATION,
   BLOCK_ENTITY_DATA,
   BLOCK_ACTION,
   BLOCK_CHANGE,
   BOSS_BAR,
   SERVER_DIFFICULTY,
   CHUNK_BATCH_END,
   CHUNK_BATCH_BEGIN,
   CHUNK_BIOMES,
   CLEAR_TITLES,
   TAB_COMPLETE,
   DECLARE_COMMANDS,
   CLOSE_WINDOW,
   WINDOW_ITEMS,
   WINDOW_PROPERTY,
   SET_SLOT,
   COOKIE_REQUEST,
   SET_COOLDOWN,
   CUSTOM_CHAT_COMPLETIONS,
   PLUGIN_MESSAGE,
   DAMAGE_EVENT,
   DEBUG_SAMPLE,
   DELETE_CHAT,
   DISCONNECT,
   DISGUISED_CHAT,
   ENTITY_STATUS,
   ENTITY_POSITION_SYNC,
   EXPLOSION,
   UNLOAD_CHUNK,
   CHANGE_GAME_STATE,
   OPEN_HORSE_WINDOW,
   HURT_ANIMATION,
   INITIALIZE_WORLD_BORDER,
   KEEP_ALIVE,
   CHUNK_DATA,
   EFFECT,
   PARTICLE,
   UPDATE_LIGHT,
   JOIN_GAME,
   MAP_DATA,
   MERCHANT_OFFERS,
   ENTITY_RELATIVE_MOVE,
   ENTITY_RELATIVE_MOVE_AND_ROTATION,
   MOVE_MINECART,
   ENTITY_ROTATION,
   VEHICLE_MOVE,
   OPEN_BOOK,
   OPEN_WINDOW,
   OPEN_SIGN_EDITOR,
   PING,
   DEBUG_PONG,
   CRAFT_RECIPE_RESPONSE,
   PLAYER_ABILITIES,
   CHAT_MESSAGE,
   END_COMBAT_EVENT,
   ENTER_COMBAT_EVENT,
   DEATH_COMBAT_EVENT,
   PLAYER_INFO_REMOVE,
   PLAYER_INFO_UPDATE,
   FACE_PLAYER,
   PLAYER_POSITION_AND_LOOK,
   PLAYER_ROTATION,
   RECIPE_BOOK_ADD,
   RECIPE_BOOK_REMOVE,
   RECIPE_BOOK_SETTINGS,
   DESTROY_ENTITIES,
   REMOVE_ENTITY_EFFECT,
   RESET_SCORE,
   RESOURCE_PACK_REMOVE,
   RESOURCE_PACK_SEND,
   RESPAWN,
   ENTITY_HEAD_LOOK,
   MULTI_BLOCK_CHANGE,
   SELECT_ADVANCEMENTS_TAB,
   SERVER_DATA,
   ACTION_BAR,
   WORLD_BORDER_CENTER,
   WORLD_BORDER_LERP_SIZE,
   WORLD_BORDER_SIZE,
   WORLD_BORDER_WARNING_DELAY,
   WORLD_BORDER_WARNING_REACH,
   CAMERA,
   UPDATE_VIEW_POSITION,
   UPDATE_VIEW_DISTANCE,
   SET_CURSOR_ITEM,
   SPAWN_POSITION,
   DISPLAY_SCOREBOARD,
   ENTITY_METADATA,
   ATTACH_ENTITY,
   ENTITY_VELOCITY,
   ENTITY_EQUIPMENT,
   SET_EXPERIENCE,
   UPDATE_HEALTH,
   HELD_ITEM_CHANGE,
   SCOREBOARD_OBJECTIVE,
   SET_PASSENGERS,
   SET_PLAYER_INVENTORY,
   TEAMS,
   UPDATE_SCORE,
   UPDATE_SIMULATION_DISTANCE,
   SET_TITLE_SUBTITLE,
   TIME_UPDATE,
   SET_TITLE_TEXT,
   SET_TITLE_TIMES,
   ENTITY_SOUND_EFFECT,
   SOUND_EFFECT,
   CONFIGURATION_START,
   STOP_SOUND,
   STORE_COOKIE,
   SYSTEM_CHAT_MESSAGE,
   PLAYER_LIST_HEADER_AND_FOOTER,
   NBT_QUERY_RESPONSE,
   COLLECT_ITEM,
   ENTITY_TELEPORT,
   TEST_INSTANCE_BLOCK_STATUS,
   TICKING_STATE,
   TICKING_STEP,
   TRANSFER,
   UPDATE_ADVANCEMENTS,
   UPDATE_ATTRIBUTES,
   ENTITY_EFFECT,
   DECLARE_RECIPES,
   TAGS,
   PROJECTILE_POWER,
   CUSTOM_REPORT_DETAILS,
   SERVER_LINKS;

   // $FF: synthetic method
   private static RV[] Y() {
      return new RV[]{BUNDLE, SPAWN_ENTITY, ENTITY_ANIMATION, STATISTICS, ACKNOWLEDGE_BLOCK_CHANGES, BLOCK_BREAK_ANIMATION, BLOCK_ENTITY_DATA, BLOCK_ACTION, BLOCK_CHANGE, BOSS_BAR, SERVER_DIFFICULTY, CHUNK_BATCH_END, CHUNK_BATCH_BEGIN, CHUNK_BIOMES, CLEAR_TITLES, TAB_COMPLETE, DECLARE_COMMANDS, CLOSE_WINDOW, WINDOW_ITEMS, WINDOW_PROPERTY, SET_SLOT, COOKIE_REQUEST, SET_COOLDOWN, CUSTOM_CHAT_COMPLETIONS, PLUGIN_MESSAGE, DAMAGE_EVENT, DEBUG_SAMPLE, DELETE_CHAT, DISCONNECT, DISGUISED_CHAT, ENTITY_STATUS, ENTITY_POSITION_SYNC, EXPLOSION, UNLOAD_CHUNK, CHANGE_GAME_STATE, OPEN_HORSE_WINDOW, HURT_ANIMATION, INITIALIZE_WORLD_BORDER, KEEP_ALIVE, CHUNK_DATA, EFFECT, PARTICLE, UPDATE_LIGHT, JOIN_GAME, MAP_DATA, MERCHANT_OFFERS, ENTITY_RELATIVE_MOVE, ENTITY_RELATIVE_MOVE_AND_ROTATION, MOVE_MINECART, ENTITY_ROTATION, VEHICLE_MOVE, OPEN_BOOK, OPEN_WINDOW, OPEN_SIGN_EDITOR, PING, DEBUG_PONG, CRAFT_RECIPE_RESPONSE, PLAYER_ABILITIES, CHAT_MESSAGE, END_COMBAT_EVENT, ENTER_COMBAT_EVENT, DEATH_COMBAT_EVENT, PLAYER_INFO_REMOVE, PLAYER_INFO_UPDATE, FACE_PLAYER, PLAYER_POSITION_AND_LOOK, PLAYER_ROTATION, RECIPE_BOOK_ADD, RECIPE_BOOK_REMOVE, RECIPE_BOOK_SETTINGS, DESTROY_ENTITIES, REMOVE_ENTITY_EFFECT, RESET_SCORE, RESOURCE_PACK_REMOVE, RESOURCE_PACK_SEND, RESPAWN, ENTITY_HEAD_LOOK, MULTI_BLOCK_CHANGE, SELECT_ADVANCEMENTS_TAB, SERVER_DATA, ACTION_BAR, WORLD_BORDER_CENTER, WORLD_BORDER_LERP_SIZE, WORLD_BORDER_SIZE, WORLD_BORDER_WARNING_DELAY, WORLD_BORDER_WARNING_REACH, CAMERA, UPDATE_VIEW_POSITION, UPDATE_VIEW_DISTANCE, SET_CURSOR_ITEM, SPAWN_POSITION, DISPLAY_SCOREBOARD, ENTITY_METADATA, ATTACH_ENTITY, ENTITY_VELOCITY, ENTITY_EQUIPMENT, SET_EXPERIENCE, UPDATE_HEALTH, HELD_ITEM_CHANGE, SCOREBOARD_OBJECTIVE, SET_PASSENGERS, SET_PLAYER_INVENTORY, TEAMS, UPDATE_SCORE, UPDATE_SIMULATION_DISTANCE, SET_TITLE_SUBTITLE, TIME_UPDATE, SET_TITLE_TEXT, SET_TITLE_TIMES, ENTITY_SOUND_EFFECT, SOUND_EFFECT, CONFIGURATION_START, STOP_SOUND, STORE_COOKIE, SYSTEM_CHAT_MESSAGE, PLAYER_LIST_HEADER_AND_FOOTER, NBT_QUERY_RESPONSE, COLLECT_ITEM, ENTITY_TELEPORT, TEST_INSTANCE_BLOCK_STATUS, TICKING_STATE, TICKING_STEP, TRANSFER, UPDATE_ADVANCEMENTS, UPDATE_ATTRIBUTES, ENTITY_EFFECT, DECLARE_RECIPES, TAGS, PROJECTILE_POWER, CUSTOM_REPORT_DETAILS, SERVER_LINKS};
   }

   static {
      long var0 = kt.a(-6465262054855988209L, -3997331236512091352L, MethodHandles.lookup().lookupClass()).a(77550732310562L) ^ 39992117870380L;
      BUNDLE = new RV("BUNDLE", 0);
      SPAWN_ENTITY = new RV("SPAWN_ENTITY", 1);
      ENTITY_ANIMATION = new RV("ENTITY_ANIMATION", 2);
      STATISTICS = new RV("STATISTICS", 3);
      ACKNOWLEDGE_BLOCK_CHANGES = new RV("ACKNOWLEDGE_BLOCK_CHANGES", 4);
      BLOCK_BREAK_ANIMATION = new RV("BLOCK_BREAK_ANIMATION", 5);
      BLOCK_ENTITY_DATA = new RV("BLOCK_ENTITY_DATA", 6);
      BLOCK_ACTION = new RV("BLOCK_ACTION", 7);
      BLOCK_CHANGE = new RV("BLOCK_CHANGE", 8);
      BOSS_BAR = new RV("BOSS_BAR", 9);
      SERVER_DIFFICULTY = new RV("SERVER_DIFFICULTY", 10);
      CHUNK_BATCH_END = new RV("CHUNK_BATCH_END", 11);
      CHUNK_BATCH_BEGIN = new RV("CHUNK_BATCH_BEGIN", 12);
      CHUNK_BIOMES = new RV("CHUNK_BIOMES", 13);
      CLEAR_TITLES = new RV("CLEAR_TITLES", 14);
      TAB_COMPLETE = new RV("TAB_COMPLETE", 15);
      DECLARE_COMMANDS = new RV("DECLARE_COMMANDS", 16);
      CLOSE_WINDOW = new RV("CLOSE_WINDOW", 17);
      WINDOW_ITEMS = new RV("WINDOW_ITEMS", 18);
      WINDOW_PROPERTY = new RV("WINDOW_PROPERTY", 19);
      SET_SLOT = new RV("SET_SLOT", 20);
      COOKIE_REQUEST = new RV("COOKIE_REQUEST", 21);
      SET_COOLDOWN = new RV("SET_COOLDOWN", 22);
      CUSTOM_CHAT_COMPLETIONS = new RV("CUSTOM_CHAT_COMPLETIONS", 23);
      PLUGIN_MESSAGE = new RV("PLUGIN_MESSAGE", 24);
      DAMAGE_EVENT = new RV("DAMAGE_EVENT", 25);
      DEBUG_SAMPLE = new RV("DEBUG_SAMPLE", 26);
      DELETE_CHAT = new RV("DELETE_CHAT", 27);
      DISCONNECT = new RV("DISCONNECT", 28);
      DISGUISED_CHAT = new RV("DISGUISED_CHAT", 29);
      ENTITY_STATUS = new RV("ENTITY_STATUS", 30);
      ENTITY_POSITION_SYNC = new RV("ENTITY_POSITION_SYNC", 31);
      EXPLOSION = new RV("EXPLOSION", 32);
      UNLOAD_CHUNK = new RV("UNLOAD_CHUNK", 33);
      CHANGE_GAME_STATE = new RV("CHANGE_GAME_STATE", 34);
      OPEN_HORSE_WINDOW = new RV("OPEN_HORSE_WINDOW", 35);
      HURT_ANIMATION = new RV("HURT_ANIMATION", 36);
      INITIALIZE_WORLD_BORDER = new RV("INITIALIZE_WORLD_BORDER", 37);
      KEEP_ALIVE = new RV("KEEP_ALIVE", 38);
      CHUNK_DATA = new RV("CHUNK_DATA", 39);
      EFFECT = new RV("EFFECT", 40);
      PARTICLE = new RV("PARTICLE", 41);
      UPDATE_LIGHT = new RV("UPDATE_LIGHT", 42);
      JOIN_GAME = new RV("JOIN_GAME", 43);
      MAP_DATA = new RV("MAP_DATA", 44);
      MERCHANT_OFFERS = new RV("MERCHANT_OFFERS", 45);
      ENTITY_RELATIVE_MOVE = new RV("ENTITY_RELATIVE_MOVE", 46);
      ENTITY_RELATIVE_MOVE_AND_ROTATION = new RV("ENTITY_RELATIVE_MOVE_AND_ROTATION", 47);
      MOVE_MINECART = new RV("MOVE_MINECART", 48);
      ENTITY_ROTATION = new RV("ENTITY_ROTATION", 49);
      VEHICLE_MOVE = new RV("VEHICLE_MOVE", 50);
      OPEN_BOOK = new RV("OPEN_BOOK", 51);
      OPEN_WINDOW = new RV("OPEN_WINDOW", 52);
      OPEN_SIGN_EDITOR = new RV("OPEN_SIGN_EDITOR", 53);
      PING = new RV("PING", 54);
      DEBUG_PONG = new RV("DEBUG_PONG", 55);
      CRAFT_RECIPE_RESPONSE = new RV("CRAFT_RECIPE_RESPONSE", 56);
      PLAYER_ABILITIES = new RV("PLAYER_ABILITIES", 57);
      CHAT_MESSAGE = new RV("CHAT_MESSAGE", 58);
      END_COMBAT_EVENT = new RV("END_COMBAT_EVENT", 59);
      ENTER_COMBAT_EVENT = new RV("ENTER_COMBAT_EVENT", 60);
      DEATH_COMBAT_EVENT = new RV("DEATH_COMBAT_EVENT", 61);
      PLAYER_INFO_REMOVE = new RV("PLAYER_INFO_REMOVE", 62);
      PLAYER_INFO_UPDATE = new RV("PLAYER_INFO_UPDATE", 63);
      FACE_PLAYER = new RV("FACE_PLAYER", 64);
      PLAYER_POSITION_AND_LOOK = new RV("PLAYER_POSITION_AND_LOOK", 65);
      PLAYER_ROTATION = new RV("PLAYER_ROTATION", 66);
      RECIPE_BOOK_ADD = new RV("RECIPE_BOOK_ADD", 67);
      RECIPE_BOOK_REMOVE = new RV("RECIPE_BOOK_REMOVE", 68);
      RECIPE_BOOK_SETTINGS = new RV("RECIPE_BOOK_SETTINGS", 69);
      DESTROY_ENTITIES = new RV("DESTROY_ENTITIES", 70);
      REMOVE_ENTITY_EFFECT = new RV("REMOVE_ENTITY_EFFECT", 71);
      RESET_SCORE = new RV("RESET_SCORE", 72);
      RESOURCE_PACK_REMOVE = new RV("RESOURCE_PACK_REMOVE", 73);
      RESOURCE_PACK_SEND = new RV("RESOURCE_PACK_SEND", 74);
      RESPAWN = new RV("RESPAWN", 75);
      ENTITY_HEAD_LOOK = new RV("ENTITY_HEAD_LOOK", 76);
      MULTI_BLOCK_CHANGE = new RV("MULTI_BLOCK_CHANGE", 77);
      SELECT_ADVANCEMENTS_TAB = new RV("SELECT_ADVANCEMENTS_TAB", 78);
      SERVER_DATA = new RV("SERVER_DATA", 79);
      ACTION_BAR = new RV("ACTION_BAR", 80);
      WORLD_BORDER_CENTER = new RV("WORLD_BORDER_CENTER", 81);
      WORLD_BORDER_LERP_SIZE = new RV("WORLD_BORDER_LERP_SIZE", 82);
      WORLD_BORDER_SIZE = new RV("WORLD_BORDER_SIZE", 83);
      WORLD_BORDER_WARNING_DELAY = new RV("WORLD_BORDER_WARNING_DELAY", 84);
      WORLD_BORDER_WARNING_REACH = new RV("WORLD_BORDER_WARNING_REACH", 85);
      CAMERA = new RV("CAMERA", 86);
      UPDATE_VIEW_POSITION = new RV("UPDATE_VIEW_POSITION", 87);
      UPDATE_VIEW_DISTANCE = new RV("UPDATE_VIEW_DISTANCE", 88);
      SET_CURSOR_ITEM = new RV("SET_CURSOR_ITEM", 89);
      SPAWN_POSITION = new RV("SPAWN_POSITION", 90);
      DISPLAY_SCOREBOARD = new RV("DISPLAY_SCOREBOARD", 91);
      ENTITY_METADATA = new RV("ENTITY_METADATA", 92);
      ATTACH_ENTITY = new RV("ATTACH_ENTITY", 93);
      ENTITY_VELOCITY = new RV("ENTITY_VELOCITY", 94);
      ENTITY_EQUIPMENT = new RV("ENTITY_EQUIPMENT", 95);
      SET_EXPERIENCE = new RV("SET_EXPERIENCE", 96);
      UPDATE_HEALTH = new RV("UPDATE_HEALTH", 97);
      HELD_ITEM_CHANGE = new RV("HELD_ITEM_CHANGE", 98);
      SCOREBOARD_OBJECTIVE = new RV("SCOREBOARD_OBJECTIVE", 99);
      SET_PASSENGERS = new RV("SET_PASSENGERS", 100);
      SET_PLAYER_INVENTORY = new RV("SET_PLAYER_INVENTORY", 101);
      TEAMS = new RV("TEAMS", 102);
      UPDATE_SCORE = new RV("UPDATE_SCORE", 103);
      UPDATE_SIMULATION_DISTANCE = new RV("UPDATE_SIMULATION_DISTANCE", 104);
      SET_TITLE_SUBTITLE = new RV("SET_TITLE_SUBTITLE", 105);
      TIME_UPDATE = new RV("TIME_UPDATE", 106);
      SET_TITLE_TEXT = new RV("SET_TITLE_TEXT", 107);
      SET_TITLE_TIMES = new RV("SET_TITLE_TIMES", 108);
      ENTITY_SOUND_EFFECT = new RV("ENTITY_SOUND_EFFECT", 109);
      SOUND_EFFECT = new RV("SOUND_EFFECT", 110);
      CONFIGURATION_START = new RV("CONFIGURATION_START", 111);
      STOP_SOUND = new RV("STOP_SOUND", 112);
      STORE_COOKIE = new RV("STORE_COOKIE", 113);
      SYSTEM_CHAT_MESSAGE = new RV("SYSTEM_CHAT_MESSAGE", 114);
      PLAYER_LIST_HEADER_AND_FOOTER = new RV("PLAYER_LIST_HEADER_AND_FOOTER", 115);
      NBT_QUERY_RESPONSE = new RV("NBT_QUERY_RESPONSE", 116);
      COLLECT_ITEM = new RV("COLLECT_ITEM", 117);
      ENTITY_TELEPORT = new RV("ENTITY_TELEPORT", 118);
      TEST_INSTANCE_BLOCK_STATUS = new RV("TEST_INSTANCE_BLOCK_STATUS", 119);
      TICKING_STATE = new RV("TICKING_STATE", 120);
      TICKING_STEP = new RV("TICKING_STEP", 121);
      TRANSFER = new RV("TRANSFER", 122);
      UPDATE_ADVANCEMENTS = new RV("UPDATE_ADVANCEMENTS", 123);
      UPDATE_ATTRIBUTES = new RV("UPDATE_ATTRIBUTES", 124);
      ENTITY_EFFECT = new RV("ENTITY_EFFECT", 125);
      DECLARE_RECIPES = new RV("DECLARE_RECIPES", 126);
      TAGS = new RV("TAGS", 127);
      PROJECTILE_POWER = new RV("PROJECTILE_POWER", 128);
      CUSTOM_REPORT_DETAILS = new RV("CUSTOM_REPORT_DETAILS", 129);
      SERVER_LINKS = new RV("SERVER_LINKS", 130);
   }
}
