package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum T6 {
   TELEPORT_CONFIRM,
   TAB_COMPLETE,
   CHAT_MESSAGE,
   CLIENT_STATUS,
   CLIENT_SETTINGS,
   WINDOW_CONFIRMATION,
   CLICK_WINDOW_BUTTON,
   CLICK_WINDOW,
   CLOSE_WINDOW,
   PLUGIN_MESSAGE,
   INTERACT_ENTITY,
   KEEP_ALIVE,
   PLAYER_FLYING,
   PLAYER_POSITION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_ROTATION,
   VEHICLE_MOVE,
   STEER_BOAT,
   CRAFT_RECIPE_REQUEST,
   PLAYER_ABILITIES,
   PLAYER_DIGGING,
   ENTITY_ACTION,
   STEER_VEHICLE,
   RECIPE_BOOK_DATA,
   RESOURCE_PACK_STATUS,
   ADVANCEMENT_TAB,
   HELD_ITEM_CHANGE,
   CREATIVE_INVENTORY_ACTION,
   UPDATE_SIGN,
   ANIMATION,
   SPECTATE,
   PLAYER_BLOCK_PLACEMENT,
   USE_ITEM;

   // $FF: synthetic method
   private static T6[] P() {
      return new T6[]{TELEPORT_CONFIRM, TAB_COMPLETE, CHAT_MESSAGE, CLIENT_STATUS, CLIENT_SETTINGS, WINDOW_CONFIRMATION, CLICK_WINDOW_BUTTON, CLICK_WINDOW, CLOSE_WINDOW, PLUGIN_MESSAGE, INTERACT_ENTITY, KEEP_ALIVE, PLAYER_FLYING, PLAYER_POSITION, PLAYER_POSITION_AND_ROTATION, PLAYER_ROTATION, VEHICLE_MOVE, STEER_BOAT, CRAFT_RECIPE_REQUEST, PLAYER_ABILITIES, PLAYER_DIGGING, ENTITY_ACTION, STEER_VEHICLE, RECIPE_BOOK_DATA, RESOURCE_PACK_STATUS, ADVANCEMENT_TAB, HELD_ITEM_CHANGE, CREATIVE_INVENTORY_ACTION, UPDATE_SIGN, ANIMATION, SPECTATE, PLAYER_BLOCK_PLACEMENT, USE_ITEM};
   }

   static {
      long var0 = kt.a(4638739018138690443L, -7091275049260112384L, MethodHandles.lookup().lookupClass()).a(77179301812917L) ^ 102526498203635L;
      TELEPORT_CONFIRM = new T6("TELEPORT_CONFIRM", 0);
      TAB_COMPLETE = new T6("TAB_COMPLETE", 1);
      CHAT_MESSAGE = new T6("CHAT_MESSAGE", 2);
      CLIENT_STATUS = new T6("CLIENT_STATUS", 3);
      CLIENT_SETTINGS = new T6("CLIENT_SETTINGS", 4);
      WINDOW_CONFIRMATION = new T6("WINDOW_CONFIRMATION", 5);
      CLICK_WINDOW_BUTTON = new T6("CLICK_WINDOW_BUTTON", 6);
      CLICK_WINDOW = new T6("CLICK_WINDOW", 7);
      CLOSE_WINDOW = new T6("CLOSE_WINDOW", 8);
      PLUGIN_MESSAGE = new T6("PLUGIN_MESSAGE", 9);
      INTERACT_ENTITY = new T6("INTERACT_ENTITY", 10);
      KEEP_ALIVE = new T6("KEEP_ALIVE", 11);
      PLAYER_FLYING = new T6("PLAYER_FLYING", 12);
      PLAYER_POSITION = new T6("PLAYER_POSITION", 13);
      PLAYER_POSITION_AND_ROTATION = new T6("PLAYER_POSITION_AND_ROTATION", 14);
      PLAYER_ROTATION = new T6("PLAYER_ROTATION", 15);
      VEHICLE_MOVE = new T6("VEHICLE_MOVE", 16);
      STEER_BOAT = new T6("STEER_BOAT", 17);
      CRAFT_RECIPE_REQUEST = new T6("CRAFT_RECIPE_REQUEST", 18);
      PLAYER_ABILITIES = new T6("PLAYER_ABILITIES", 19);
      PLAYER_DIGGING = new T6("PLAYER_DIGGING", 20);
      ENTITY_ACTION = new T6("ENTITY_ACTION", 21);
      STEER_VEHICLE = new T6("STEER_VEHICLE", 22);
      RECIPE_BOOK_DATA = new T6("RECIPE_BOOK_DATA", 23);
      RESOURCE_PACK_STATUS = new T6("RESOURCE_PACK_STATUS", 24);
      ADVANCEMENT_TAB = new T6("ADVANCEMENT_TAB", 25);
      HELD_ITEM_CHANGE = new T6("HELD_ITEM_CHANGE", 26);
      CREATIVE_INVENTORY_ACTION = new T6("CREATIVE_INVENTORY_ACTION", 27);
      UPDATE_SIGN = new T6("UPDATE_SIGN", 28);
      ANIMATION = new T6("ANIMATION", 29);
      SPECTATE = new T6("SPECTATE", 30);
      PLAYER_BLOCK_PLACEMENT = new T6("PLAYER_BLOCK_PLACEMENT", 31);
      USE_ITEM = new T6("USE_ITEM", 32);
   }
}
