package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum Tm {
   SPAWN_ENTITY,
   SPAWN_EXPERIENCE_ORB,
   SPAWN_PLAYER,
   ENTITY_ANIMATION,
   STATISTICS,
   ACKNOWLEDGE_BLOCK_CHANGES,
   BLOCK_BREAK_ANIMATION,
   BLOCK_ENTITY_DATA,
   BLOCK_ACTION,
   BLOCK_CHANGE,
   BOSS_BAR,
   SERVER_DIFFICULTY,
   CHAT_PREVIEW_PACKET,
   CLEAR_TITLES,
   TAB_COMPLETE,
   DECLARE_COMMANDS,
   CLOSE_WINDOW,
   WINDOW_ITEMS,
   WINDOW_PROPERTY,
   SET_SLOT,
   SET_COOLDOWN,
   PLUGIN_MESSAGE,
   NAMED_SOUND_EFFECT,
   DISCONNECT,
   ENTITY_STATUS,
   EXPLOSION,
   UNLOAD_CHUNK,
   CHANGE_GAME_STATE,
   OPEN_HORSE_WINDOW,
   INITIALIZE_WORLD_BORDER,
   KEEP_ALIVE,
   CHUNK_DATA,
   EFFECT,
   PARTICLE,
   UPDATE_LIGHT,
   JOIN_GAME,
   MAP_DATA,
   MERCHANT_OFFERS,
   ENTITY_RELATIVE_MOVE,
   ENTITY_RELATIVE_MOVE_AND_ROTATION,
   ENTITY_ROTATION,
   VEHICLE_MOVE,
   OPEN_BOOK,
   OPEN_WINDOW,
   OPEN_SIGN_EDITOR,
   PING,
   CRAFT_RECIPE_RESPONSE,
   PLAYER_ABILITIES,
   CHAT_MESSAGE,
   END_COMBAT_EVENT,
   ENTER_COMBAT_EVENT,
   DEATH_COMBAT_EVENT,
   PLAYER_INFO,
   FACE_PLAYER,
   PLAYER_POSITION_AND_LOOK,
   UNLOCK_RECIPES,
   DESTROY_ENTITIES,
   REMOVE_ENTITY_EFFECT,
   RESOURCE_PACK_SEND,
   RESPAWN,
   ENTITY_HEAD_LOOK,
   MULTI_BLOCK_CHANGE,
   SELECT_ADVANCEMENTS_TAB,
   SERVER_DATA,
   ACTION_BAR,
   WORLD_BORDER_CENTER,
   WORLD_BORDER_LERP_SIZE,
   WORLD_BORDER_SIZE,
   WORLD_BORDER_WARNING_DELAY,
   WORLD_BORDER_WARNING_REACH,
   CAMERA,
   HELD_ITEM_CHANGE,
   UPDATE_VIEW_POSITION,
   UPDATE_VIEW_DISTANCE,
   SPAWN_POSITION,
   DISPLAY_CHAT_PREVIEW,
   DISPLAY_SCOREBOARD,
   ENTITY_METADATA,
   ATTACH_ENTITY,
   ENTITY_VELOCITY,
   ENTITY_EQUIPMENT,
   SET_EXPERIENCE,
   UPDATE_HEALTH,
   SCOREBOARD_OBJECTIVE,
   SET_PASSENGERS,
   TEAMS,
   UPDATE_SCORE,
   UPDATE_SIMULATION_DISTANCE,
   SET_TITLE_SUBTITLE,
   TIME_UPDATE,
   SET_TITLE_TEXT,
   SET_TITLE_TIMES,
   ENTITY_SOUND_EFFECT,
   SOUND_EFFECT,
   STOP_SOUND,
   SYSTEM_CHAT_MESSAGE,
   PLAYER_LIST_HEADER_AND_FOOTER,
   NBT_QUERY_RESPONSE,
   COLLECT_ITEM,
   ENTITY_TELEPORT,
   UPDATE_ADVANCEMENTS,
   UPDATE_ATTRIBUTES,
   ENTITY_EFFECT,
   DECLARE_RECIPES,
   TAGS;

   // $FF: synthetic method
   private static Tm[] V() {
      return new Tm[]{SPAWN_ENTITY, SPAWN_EXPERIENCE_ORB, SPAWN_PLAYER, ENTITY_ANIMATION, STATISTICS, ACKNOWLEDGE_BLOCK_CHANGES, BLOCK_BREAK_ANIMATION, BLOCK_ENTITY_DATA, BLOCK_ACTION, BLOCK_CHANGE, BOSS_BAR, SERVER_DIFFICULTY, CHAT_PREVIEW_PACKET, CLEAR_TITLES, TAB_COMPLETE, DECLARE_COMMANDS, CLOSE_WINDOW, WINDOW_ITEMS, WINDOW_PROPERTY, SET_SLOT, SET_COOLDOWN, PLUGIN_MESSAGE, NAMED_SOUND_EFFECT, DISCONNECT, ENTITY_STATUS, EXPLOSION, UNLOAD_CHUNK, CHANGE_GAME_STATE, OPEN_HORSE_WINDOW, INITIALIZE_WORLD_BORDER, KEEP_ALIVE, CHUNK_DATA, EFFECT, PARTICLE, UPDATE_LIGHT, JOIN_GAME, MAP_DATA, MERCHANT_OFFERS, ENTITY_RELATIVE_MOVE, ENTITY_RELATIVE_MOVE_AND_ROTATION, ENTITY_ROTATION, VEHICLE_MOVE, OPEN_BOOK, OPEN_WINDOW, OPEN_SIGN_EDITOR, PING, CRAFT_RECIPE_RESPONSE, PLAYER_ABILITIES, CHAT_MESSAGE, END_COMBAT_EVENT, ENTER_COMBAT_EVENT, DEATH_COMBAT_EVENT, PLAYER_INFO, FACE_PLAYER, PLAYER_POSITION_AND_LOOK, UNLOCK_RECIPES, DESTROY_ENTITIES, REMOVE_ENTITY_EFFECT, RESOURCE_PACK_SEND, RESPAWN, ENTITY_HEAD_LOOK, MULTI_BLOCK_CHANGE, SELECT_ADVANCEMENTS_TAB, SERVER_DATA, ACTION_BAR, WORLD_BORDER_CENTER, WORLD_BORDER_LERP_SIZE, WORLD_BORDER_SIZE, WORLD_BORDER_WARNING_DELAY, WORLD_BORDER_WARNING_REACH, CAMERA, HELD_ITEM_CHANGE, UPDATE_VIEW_POSITION, UPDATE_VIEW_DISTANCE, SPAWN_POSITION, DISPLAY_CHAT_PREVIEW, DISPLAY_SCOREBOARD, ENTITY_METADATA, ATTACH_ENTITY, ENTITY_VELOCITY, ENTITY_EQUIPMENT, SET_EXPERIENCE, UPDATE_HEALTH, SCOREBOARD_OBJECTIVE, SET_PASSENGERS, TEAMS, UPDATE_SCORE, UPDATE_SIMULATION_DISTANCE, SET_TITLE_SUBTITLE, TIME_UPDATE, SET_TITLE_TEXT, SET_TITLE_TIMES, ENTITY_SOUND_EFFECT, SOUND_EFFECT, STOP_SOUND, SYSTEM_CHAT_MESSAGE, PLAYER_LIST_HEADER_AND_FOOTER, NBT_QUERY_RESPONSE, COLLECT_ITEM, ENTITY_TELEPORT, UPDATE_ADVANCEMENTS, UPDATE_ATTRIBUTES, ENTITY_EFFECT, DECLARE_RECIPES, TAGS};
   }

   static {
      long var0 = kt.a(2620313200065845546L, 4510583647561482565L, MethodHandles.lookup().lookupClass()).a(152854801186090L) ^ 61061183135314L;
      SPAWN_ENTITY = new Tm("SPAWN_ENTITY", 0);
      SPAWN_EXPERIENCE_ORB = new Tm("SPAWN_EXPERIENCE_ORB", 1);
      SPAWN_PLAYER = new Tm("SPAWN_PLAYER", 2);
      ENTITY_ANIMATION = new Tm("ENTITY_ANIMATION", 3);
      STATISTICS = new Tm("STATISTICS", 4);
      ACKNOWLEDGE_BLOCK_CHANGES = new Tm("ACKNOWLEDGE_BLOCK_CHANGES", 5);
      BLOCK_BREAK_ANIMATION = new Tm("BLOCK_BREAK_ANIMATION", 6);
      BLOCK_ENTITY_DATA = new Tm("BLOCK_ENTITY_DATA", 7);
      BLOCK_ACTION = new Tm("BLOCK_ACTION", 8);
      BLOCK_CHANGE = new Tm("BLOCK_CHANGE", 9);
      BOSS_BAR = new Tm("BOSS_BAR", 10);
      SERVER_DIFFICULTY = new Tm("SERVER_DIFFICULTY", 11);
      CHAT_PREVIEW_PACKET = new Tm("CHAT_PREVIEW_PACKET", 12);
      CLEAR_TITLES = new Tm("CLEAR_TITLES", 13);
      TAB_COMPLETE = new Tm("TAB_COMPLETE", 14);
      DECLARE_COMMANDS = new Tm("DECLARE_COMMANDS", 15);
      CLOSE_WINDOW = new Tm("CLOSE_WINDOW", 16);
      WINDOW_ITEMS = new Tm("WINDOW_ITEMS", 17);
      WINDOW_PROPERTY = new Tm("WINDOW_PROPERTY", 18);
      SET_SLOT = new Tm("SET_SLOT", 19);
      SET_COOLDOWN = new Tm("SET_COOLDOWN", 20);
      PLUGIN_MESSAGE = new Tm("PLUGIN_MESSAGE", 21);
      NAMED_SOUND_EFFECT = new Tm("NAMED_SOUND_EFFECT", 22);
      DISCONNECT = new Tm("DISCONNECT", 23);
      ENTITY_STATUS = new Tm("ENTITY_STATUS", 24);
      EXPLOSION = new Tm("EXPLOSION", 25);
      UNLOAD_CHUNK = new Tm("UNLOAD_CHUNK", 26);
      CHANGE_GAME_STATE = new Tm("CHANGE_GAME_STATE", 27);
      OPEN_HORSE_WINDOW = new Tm("OPEN_HORSE_WINDOW", 28);
      INITIALIZE_WORLD_BORDER = new Tm("INITIALIZE_WORLD_BORDER", 29);
      KEEP_ALIVE = new Tm("KEEP_ALIVE", 30);
      CHUNK_DATA = new Tm("CHUNK_DATA", 31);
      EFFECT = new Tm("EFFECT", 32);
      PARTICLE = new Tm("PARTICLE", 33);
      UPDATE_LIGHT = new Tm("UPDATE_LIGHT", 34);
      JOIN_GAME = new Tm("JOIN_GAME", 35);
      MAP_DATA = new Tm("MAP_DATA", 36);
      MERCHANT_OFFERS = new Tm("MERCHANT_OFFERS", 37);
      ENTITY_RELATIVE_MOVE = new Tm("ENTITY_RELATIVE_MOVE", 38);
      ENTITY_RELATIVE_MOVE_AND_ROTATION = new Tm("ENTITY_RELATIVE_MOVE_AND_ROTATION", 39);
      ENTITY_ROTATION = new Tm("ENTITY_ROTATION", 40);
      VEHICLE_MOVE = new Tm("VEHICLE_MOVE", 41);
      OPEN_BOOK = new Tm("OPEN_BOOK", 42);
      OPEN_WINDOW = new Tm("OPEN_WINDOW", 43);
      OPEN_SIGN_EDITOR = new Tm("OPEN_SIGN_EDITOR", 44);
      PING = new Tm("PING", 45);
      CRAFT_RECIPE_RESPONSE = new Tm("CRAFT_RECIPE_RESPONSE", 46);
      PLAYER_ABILITIES = new Tm("PLAYER_ABILITIES", 47);
      CHAT_MESSAGE = new Tm("CHAT_MESSAGE", 48);
      END_COMBAT_EVENT = new Tm("END_COMBAT_EVENT", 49);
      ENTER_COMBAT_EVENT = new Tm("ENTER_COMBAT_EVENT", 50);
      DEATH_COMBAT_EVENT = new Tm("DEATH_COMBAT_EVENT", 51);
      PLAYER_INFO = new Tm("PLAYER_INFO", 52);
      FACE_PLAYER = new Tm("FACE_PLAYER", 53);
      PLAYER_POSITION_AND_LOOK = new Tm("PLAYER_POSITION_AND_LOOK", 54);
      UNLOCK_RECIPES = new Tm("UNLOCK_RECIPES", 55);
      DESTROY_ENTITIES = new Tm("DESTROY_ENTITIES", 56);
      REMOVE_ENTITY_EFFECT = new Tm("REMOVE_ENTITY_EFFECT", 57);
      RESOURCE_PACK_SEND = new Tm("RESOURCE_PACK_SEND", 58);
      RESPAWN = new Tm("RESPAWN", 59);
      ENTITY_HEAD_LOOK = new Tm("ENTITY_HEAD_LOOK", 60);
      MULTI_BLOCK_CHANGE = new Tm("MULTI_BLOCK_CHANGE", 61);
      SELECT_ADVANCEMENTS_TAB = new Tm("SELECT_ADVANCEMENTS_TAB", 62);
      SERVER_DATA = new Tm("SERVER_DATA", 63);
      ACTION_BAR = new Tm("ACTION_BAR", 64);
      WORLD_BORDER_CENTER = new Tm("WORLD_BORDER_CENTER", 65);
      WORLD_BORDER_LERP_SIZE = new Tm("WORLD_BORDER_LERP_SIZE", 66);
      WORLD_BORDER_SIZE = new Tm("WORLD_BORDER_SIZE", 67);
      WORLD_BORDER_WARNING_DELAY = new Tm("WORLD_BORDER_WARNING_DELAY", 68);
      WORLD_BORDER_WARNING_REACH = new Tm("WORLD_BORDER_WARNING_REACH", 69);
      CAMERA = new Tm("CAMERA", 70);
      HELD_ITEM_CHANGE = new Tm("HELD_ITEM_CHANGE", 71);
      UPDATE_VIEW_POSITION = new Tm("UPDATE_VIEW_POSITION", 72);
      UPDATE_VIEW_DISTANCE = new Tm("UPDATE_VIEW_DISTANCE", 73);
      SPAWN_POSITION = new Tm("SPAWN_POSITION", 74);
      DISPLAY_CHAT_PREVIEW = new Tm("DISPLAY_CHAT_PREVIEW", 75);
      DISPLAY_SCOREBOARD = new Tm("DISPLAY_SCOREBOARD", 76);
      ENTITY_METADATA = new Tm("ENTITY_METADATA", 77);
      ATTACH_ENTITY = new Tm("ATTACH_ENTITY", 78);
      ENTITY_VELOCITY = new Tm("ENTITY_VELOCITY", 79);
      ENTITY_EQUIPMENT = new Tm("ENTITY_EQUIPMENT", 80);
      SET_EXPERIENCE = new Tm("SET_EXPERIENCE", 81);
      UPDATE_HEALTH = new Tm("UPDATE_HEALTH", 82);
      SCOREBOARD_OBJECTIVE = new Tm("SCOREBOARD_OBJECTIVE", 83);
      SET_PASSENGERS = new Tm("SET_PASSENGERS", 84);
      TEAMS = new Tm("TEAMS", 85);
      UPDATE_SCORE = new Tm("UPDATE_SCORE", 86);
      UPDATE_SIMULATION_DISTANCE = new Tm("UPDATE_SIMULATION_DISTANCE", 87);
      SET_TITLE_SUBTITLE = new Tm("SET_TITLE_SUBTITLE", 88);
      TIME_UPDATE = new Tm("TIME_UPDATE", 89);
      SET_TITLE_TEXT = new Tm("SET_TITLE_TEXT", 90);
      SET_TITLE_TIMES = new Tm("SET_TITLE_TIMES", 91);
      ENTITY_SOUND_EFFECT = new Tm("ENTITY_SOUND_EFFECT", 92);
      SOUND_EFFECT = new Tm("SOUND_EFFECT", 93);
      STOP_SOUND = new Tm("STOP_SOUND", 94);
      SYSTEM_CHAT_MESSAGE = new Tm("SYSTEM_CHAT_MESSAGE", 95);
      PLAYER_LIST_HEADER_AND_FOOTER = new Tm("PLAYER_LIST_HEADER_AND_FOOTER", 96);
      NBT_QUERY_RESPONSE = new Tm("NBT_QUERY_RESPONSE", 97);
      COLLECT_ITEM = new Tm("COLLECT_ITEM", 98);
      ENTITY_TELEPORT = new Tm("ENTITY_TELEPORT", 99);
      UPDATE_ADVANCEMENTS = new Tm("UPDATE_ADVANCEMENTS", 100);
      UPDATE_ATTRIBUTES = new Tm("UPDATE_ATTRIBUTES", 101);
      ENTITY_EFFECT = new Tm("ENTITY_EFFECT", 102);
      DECLARE_RECIPES = new Tm("DECLARE_RECIPES", 103);
      TAGS = new Tm("TAGS", 104);
   }
}
