package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum U {
   BUNDLE,
   SPAWN_ENTITY,
   SPAWN_EXPERIENCE_ORB,
   SPAWN_PLAYER,
   ENTITY_ANIMATION,
   STATISTICS,
   ACKNOWLEDGE_BLOCK_CHANGES,
   BLOCK_BREAK_ANIMATION,
   BLOCK_ENTITY_DATA,
   BLOCK_ACTION,
   BLOCK_CHANGE,
   BOSS_BAR,
   SERVER_DIFFICULTY,
   CHUNK_BIOMES,
   CLEAR_TITLES,
   TAB_COMPLETE,
   DECLARE_COMMANDS,
   CLOSE_WINDOW,
   WINDOW_ITEMS,
   WINDOW_PROPERTY,
   SET_SLOT,
   SET_COOLDOWN,
   CUSTOM_CHAT_COMPLETIONS,
   PLUGIN_MESSAGE,
   DAMAGE_EVENT,
   DELETE_CHAT,
   DISCONNECT,
   DISGUISED_CHAT,
   ENTITY_STATUS,
   EXPLOSION,
   UNLOAD_CHUNK,
   CHANGE_GAME_STATE,
   OPEN_HORSE_WINDOW,
   HURT_ANIMATION,
   INITIALIZE_WORLD_BORDER,
   KEEP_ALIVE,
   CHUNK_DATA,
   EFFECT,
   PARTICLE,
   UPDATE_LIGHT,
   JOIN_GAME,
   MAP_DATA,
   MERCHANT_OFFERS,
   ENTITY_RELATIVE_MOVE,
   ENTITY_RELATIVE_MOVE_AND_ROTATION,
   ENTITY_ROTATION,
   VEHICLE_MOVE,
   OPEN_BOOK,
   OPEN_WINDOW,
   OPEN_SIGN_EDITOR,
   PING,
   CRAFT_RECIPE_RESPONSE,
   PLAYER_ABILITIES,
   CHAT_MESSAGE,
   END_COMBAT_EVENT,
   ENTER_COMBAT_EVENT,
   DEATH_COMBAT_EVENT,
   PLAYER_INFO_REMOVE,
   PLAYER_INFO_UPDATE,
   FACE_PLAYER,
   PLAYER_POSITION_AND_LOOK,
   UNLOCK_RECIPES,
   DESTROY_ENTITIES,
   REMOVE_ENTITY_EFFECT,
   RESOURCE_PACK_SEND,
   RESPAWN,
   ENTITY_HEAD_LOOK,
   MULTI_BLOCK_CHANGE,
   SELECT_ADVANCEMENTS_TAB,
   SERVER_DATA,
   ACTION_BAR,
   WORLD_BORDER_CENTER,
   WORLD_BORDER_LERP_SIZE,
   WORLD_BORDER_SIZE,
   WORLD_BORDER_WARNING_DELAY,
   WORLD_BORDER_WARNING_REACH,
   CAMERA,
   HELD_ITEM_CHANGE,
   UPDATE_VIEW_POSITION,
   UPDATE_VIEW_DISTANCE,
   SPAWN_POSITION,
   DISPLAY_SCOREBOARD,
   ENTITY_METADATA,
   ATTACH_ENTITY,
   ENTITY_VELOCITY,
   ENTITY_EQUIPMENT,
   SET_EXPERIENCE,
   UPDATE_HEALTH,
   SCOREBOARD_OBJECTIVE,
   SET_PASSENGERS,
   TEAMS,
   UPDATE_SCORE,
   UPDATE_SIMULATION_DISTANCE,
   SET_TITLE_SUBTITLE,
   TIME_UPDATE,
   SET_TITLE_TEXT,
   SET_TITLE_TIMES,
   ENTITY_SOUND_EFFECT,
   SOUND_EFFECT,
   STOP_SOUND,
   SYSTEM_CHAT_MESSAGE,
   PLAYER_LIST_HEADER_AND_FOOTER,
   NBT_QUERY_RESPONSE,
   COLLECT_ITEM,
   ENTITY_TELEPORT,
   UPDATE_ADVANCEMENTS,
   UPDATE_ATTRIBUTES,
   UPDATE_ENABLED_FEATURES,
   ENTITY_EFFECT,
   DECLARE_RECIPES,
   TAGS;

   // $FF: synthetic method
   private static U[] f() {
      return new U[]{BUNDLE, SPAWN_ENTITY, SPAWN_EXPERIENCE_ORB, SPAWN_PLAYER, ENTITY_ANIMATION, STATISTICS, ACKNOWLEDGE_BLOCK_CHANGES, BLOCK_BREAK_ANIMATION, BLOCK_ENTITY_DATA, BLOCK_ACTION, BLOCK_CHANGE, BOSS_BAR, SERVER_DIFFICULTY, CHUNK_BIOMES, CLEAR_TITLES, TAB_COMPLETE, DECLARE_COMMANDS, CLOSE_WINDOW, WINDOW_ITEMS, WINDOW_PROPERTY, SET_SLOT, SET_COOLDOWN, CUSTOM_CHAT_COMPLETIONS, PLUGIN_MESSAGE, DAMAGE_EVENT, DELETE_CHAT, DISCONNECT, DISGUISED_CHAT, ENTITY_STATUS, EXPLOSION, UNLOAD_CHUNK, CHANGE_GAME_STATE, OPEN_HORSE_WINDOW, HURT_ANIMATION, INITIALIZE_WORLD_BORDER, KEEP_ALIVE, CHUNK_DATA, EFFECT, PARTICLE, UPDATE_LIGHT, JOIN_GAME, MAP_DATA, MERCHANT_OFFERS, ENTITY_RELATIVE_MOVE, ENTITY_RELATIVE_MOVE_AND_ROTATION, ENTITY_ROTATION, VEHICLE_MOVE, OPEN_BOOK, OPEN_WINDOW, OPEN_SIGN_EDITOR, PING, CRAFT_RECIPE_RESPONSE, PLAYER_ABILITIES, CHAT_MESSAGE, END_COMBAT_EVENT, ENTER_COMBAT_EVENT, DEATH_COMBAT_EVENT, PLAYER_INFO_REMOVE, PLAYER_INFO_UPDATE, FACE_PLAYER, PLAYER_POSITION_AND_LOOK, UNLOCK_RECIPES, DESTROY_ENTITIES, REMOVE_ENTITY_EFFECT, RESOURCE_PACK_SEND, RESPAWN, ENTITY_HEAD_LOOK, MULTI_BLOCK_CHANGE, SELECT_ADVANCEMENTS_TAB, SERVER_DATA, ACTION_BAR, WORLD_BORDER_CENTER, WORLD_BORDER_LERP_SIZE, WORLD_BORDER_SIZE, WORLD_BORDER_WARNING_DELAY, WORLD_BORDER_WARNING_REACH, CAMERA, HELD_ITEM_CHANGE, UPDATE_VIEW_POSITION, UPDATE_VIEW_DISTANCE, SPAWN_POSITION, DISPLAY_SCOREBOARD, ENTITY_METADATA, ATTACH_ENTITY, ENTITY_VELOCITY, ENTITY_EQUIPMENT, SET_EXPERIENCE, UPDATE_HEALTH, SCOREBOARD_OBJECTIVE, SET_PASSENGERS, TEAMS, UPDATE_SCORE, UPDATE_SIMULATION_DISTANCE, SET_TITLE_SUBTITLE, TIME_UPDATE, SET_TITLE_TEXT, SET_TITLE_TIMES, ENTITY_SOUND_EFFECT, SOUND_EFFECT, STOP_SOUND, SYSTEM_CHAT_MESSAGE, PLAYER_LIST_HEADER_AND_FOOTER, NBT_QUERY_RESPONSE, COLLECT_ITEM, ENTITY_TELEPORT, UPDATE_ADVANCEMENTS, UPDATE_ATTRIBUTES, UPDATE_ENABLED_FEATURES, ENTITY_EFFECT, DECLARE_RECIPES, TAGS};
   }

   static {
      long var0 = kt.a(5036177754799767910L, 1000650447060690087L, MethodHandles.lookup().lookupClass()).a(280053999893781L) ^ 47649885603576L;
      BUNDLE = new U("BUNDLE", 0);
      SPAWN_ENTITY = new U("SPAWN_ENTITY", 1);
      SPAWN_EXPERIENCE_ORB = new U("SPAWN_EXPERIENCE_ORB", 2);
      SPAWN_PLAYER = new U("SPAWN_PLAYER", 3);
      ENTITY_ANIMATION = new U("ENTITY_ANIMATION", 4);
      STATISTICS = new U("STATISTICS", 5);
      ACKNOWLEDGE_BLOCK_CHANGES = new U("ACKNOWLEDGE_BLOCK_CHANGES", 6);
      BLOCK_BREAK_ANIMATION = new U("BLOCK_BREAK_ANIMATION", 7);
      BLOCK_ENTITY_DATA = new U("BLOCK_ENTITY_DATA", 8);
      BLOCK_ACTION = new U("BLOCK_ACTION", 9);
      BLOCK_CHANGE = new U("BLOCK_CHANGE", 10);
      BOSS_BAR = new U("BOSS_BAR", 11);
      SERVER_DIFFICULTY = new U("SERVER_DIFFICULTY", 12);
      CHUNK_BIOMES = new U("CHUNK_BIOMES", 13);
      CLEAR_TITLES = new U("CLEAR_TITLES", 14);
      TAB_COMPLETE = new U("TAB_COMPLETE", 15);
      DECLARE_COMMANDS = new U("DECLARE_COMMANDS", 16);
      CLOSE_WINDOW = new U("CLOSE_WINDOW", 17);
      WINDOW_ITEMS = new U("WINDOW_ITEMS", 18);
      WINDOW_PROPERTY = new U("WINDOW_PROPERTY", 19);
      SET_SLOT = new U("SET_SLOT", 20);
      SET_COOLDOWN = new U("SET_COOLDOWN", 21);
      CUSTOM_CHAT_COMPLETIONS = new U("CUSTOM_CHAT_COMPLETIONS", 22);
      PLUGIN_MESSAGE = new U("PLUGIN_MESSAGE", 23);
      DAMAGE_EVENT = new U("DAMAGE_EVENT", 24);
      DELETE_CHAT = new U("DELETE_CHAT", 25);
      DISCONNECT = new U("DISCONNECT", 26);
      DISGUISED_CHAT = new U("DISGUISED_CHAT", 27);
      ENTITY_STATUS = new U("ENTITY_STATUS", 28);
      EXPLOSION = new U("EXPLOSION", 29);
      UNLOAD_CHUNK = new U("UNLOAD_CHUNK", 30);
      CHANGE_GAME_STATE = new U("CHANGE_GAME_STATE", 31);
      OPEN_HORSE_WINDOW = new U("OPEN_HORSE_WINDOW", 32);
      HURT_ANIMATION = new U("HURT_ANIMATION", 33);
      INITIALIZE_WORLD_BORDER = new U("INITIALIZE_WORLD_BORDER", 34);
      KEEP_ALIVE = new U("KEEP_ALIVE", 35);
      CHUNK_DATA = new U("CHUNK_DATA", 36);
      EFFECT = new U("EFFECT", 37);
      PARTICLE = new U("PARTICLE", 38);
      UPDATE_LIGHT = new U("UPDATE_LIGHT", 39);
      JOIN_GAME = new U("JOIN_GAME", 40);
      MAP_DATA = new U("MAP_DATA", 41);
      MERCHANT_OFFERS = new U("MERCHANT_OFFERS", 42);
      ENTITY_RELATIVE_MOVE = new U("ENTITY_RELATIVE_MOVE", 43);
      ENTITY_RELATIVE_MOVE_AND_ROTATION = new U("ENTITY_RELATIVE_MOVE_AND_ROTATION", 44);
      ENTITY_ROTATION = new U("ENTITY_ROTATION", 45);
      VEHICLE_MOVE = new U("VEHICLE_MOVE", 46);
      OPEN_BOOK = new U("OPEN_BOOK", 47);
      OPEN_WINDOW = new U("OPEN_WINDOW", 48);
      OPEN_SIGN_EDITOR = new U("OPEN_SIGN_EDITOR", 49);
      PING = new U("PING", 50);
      CRAFT_RECIPE_RESPONSE = new U("CRAFT_RECIPE_RESPONSE", 51);
      PLAYER_ABILITIES = new U("PLAYER_ABILITIES", 52);
      CHAT_MESSAGE = new U("CHAT_MESSAGE", 53);
      END_COMBAT_EVENT = new U("END_COMBAT_EVENT", 54);
      ENTER_COMBAT_EVENT = new U("ENTER_COMBAT_EVENT", 55);
      DEATH_COMBAT_EVENT = new U("DEATH_COMBAT_EVENT", 56);
      PLAYER_INFO_REMOVE = new U("PLAYER_INFO_REMOVE", 57);
      PLAYER_INFO_UPDATE = new U("PLAYER_INFO_UPDATE", 58);
      FACE_PLAYER = new U("FACE_PLAYER", 59);
      PLAYER_POSITION_AND_LOOK = new U("PLAYER_POSITION_AND_LOOK", 60);
      UNLOCK_RECIPES = new U("UNLOCK_RECIPES", 61);
      DESTROY_ENTITIES = new U("DESTROY_ENTITIES", 62);
      REMOVE_ENTITY_EFFECT = new U("REMOVE_ENTITY_EFFECT", 63);
      RESOURCE_PACK_SEND = new U("RESOURCE_PACK_SEND", 64);
      RESPAWN = new U("RESPAWN", 65);
      ENTITY_HEAD_LOOK = new U("ENTITY_HEAD_LOOK", 66);
      MULTI_BLOCK_CHANGE = new U("MULTI_BLOCK_CHANGE", 67);
      SELECT_ADVANCEMENTS_TAB = new U("SELECT_ADVANCEMENTS_TAB", 68);
      SERVER_DATA = new U("SERVER_DATA", 69);
      ACTION_BAR = new U("ACTION_BAR", 70);
      WORLD_BORDER_CENTER = new U("WORLD_BORDER_CENTER", 71);
      WORLD_BORDER_LERP_SIZE = new U("WORLD_BORDER_LERP_SIZE", 72);
      WORLD_BORDER_SIZE = new U("WORLD_BORDER_SIZE", 73);
      WORLD_BORDER_WARNING_DELAY = new U("WORLD_BORDER_WARNING_DELAY", 74);
      WORLD_BORDER_WARNING_REACH = new U("WORLD_BORDER_WARNING_REACH", 75);
      CAMERA = new U("CAMERA", 76);
      HELD_ITEM_CHANGE = new U("HELD_ITEM_CHANGE", 77);
      UPDATE_VIEW_POSITION = new U("UPDATE_VIEW_POSITION", 78);
      UPDATE_VIEW_DISTANCE = new U("UPDATE_VIEW_DISTANCE", 79);
      SPAWN_POSITION = new U("SPAWN_POSITION", 80);
      DISPLAY_SCOREBOARD = new U("DISPLAY_SCOREBOARD", 81);
      ENTITY_METADATA = new U("ENTITY_METADATA", 82);
      ATTACH_ENTITY = new U("ATTACH_ENTITY", 83);
      ENTITY_VELOCITY = new U("ENTITY_VELOCITY", 84);
      ENTITY_EQUIPMENT = new U("ENTITY_EQUIPMENT", 85);
      SET_EXPERIENCE = new U("SET_EXPERIENCE", 86);
      UPDATE_HEALTH = new U("UPDATE_HEALTH", 87);
      SCOREBOARD_OBJECTIVE = new U("SCOREBOARD_OBJECTIVE", 88);
      SET_PASSENGERS = new U("SET_PASSENGERS", 89);
      TEAMS = new U("TEAMS", 90);
      UPDATE_SCORE = new U("UPDATE_SCORE", 91);
      UPDATE_SIMULATION_DISTANCE = new U("UPDATE_SIMULATION_DISTANCE", 92);
      SET_TITLE_SUBTITLE = new U("SET_TITLE_SUBTITLE", 93);
      TIME_UPDATE = new U("TIME_UPDATE", 94);
      SET_TITLE_TEXT = new U("SET_TITLE_TEXT", 95);
      SET_TITLE_TIMES = new U("SET_TITLE_TIMES", 96);
      ENTITY_SOUND_EFFECT = new U("ENTITY_SOUND_EFFECT", 97);
      SOUND_EFFECT = new U("SOUND_EFFECT", 98);
      STOP_SOUND = new U("STOP_SOUND", 99);
      SYSTEM_CHAT_MESSAGE = new U("SYSTEM_CHAT_MESSAGE", 100);
      PLAYER_LIST_HEADER_AND_FOOTER = new U("PLAYER_LIST_HEADER_AND_FOOTER", 101);
      NBT_QUERY_RESPONSE = new U("NBT_QUERY_RESPONSE", 102);
      COLLECT_ITEM = new U("COLLECT_ITEM", 103);
      ENTITY_TELEPORT = new U("ENTITY_TELEPORT", 104);
      UPDATE_ADVANCEMENTS = new U("UPDATE_ADVANCEMENTS", 105);
      UPDATE_ATTRIBUTES = new U("UPDATE_ATTRIBUTES", 106);
      UPDATE_ENABLED_FEATURES = new U("UPDATE_ENABLED_FEATURES", 107);
      ENTITY_EFFECT = new U("ENTITY_EFFECT", 108);
      DECLARE_RECIPES = new U("DECLARE_RECIPES", 109);
      TAGS = new U("TAGS", 110);
   }
}
