package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum u8 {
   TELEPORT_CONFIRM,
   QUERY_BLOCK_NBT,
   SET_DIFFICULTY,
   CHAT_ACK,
   CHAT_COMMAND,
   CHAT_MESSAGE,
   CHAT_SESSION_UPDATE,
   CHUNK_BATCH_ACK,
   CLIENT_STATUS,
   CLIENT_SETTINGS,
   TAB_COMPLETE,
   CONFIGURATION_ACK,
   CLICK_WINDOW_BUTTON,
   CLICK_WINDOW,
   CLOSE_WINDOW,
   PLUGIN_MESSAGE,
   EDIT_BOOK,
   QUERY_ENTITY_NBT,
   INTERACT_ENTITY,
   GENERATE_STRUCTURE,
   KEEP_ALIVE,
   LOCK_DIFFICULTY,
   PLAYER_POSITION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_ROTATION,
   PLAYER_FLYING,
   VEHICLE_MOVE,
   STEER_BOAT,
   PICK_ITEM,
   DEBUG_PING,
   CRAFT_RECIPE_REQUEST,
   PLAYER_ABILITIES,
   PLAYER_DIGGING,
   ENTITY_ACTION,
   STEER_VEHICLE,
   PONG,
   SET_RECIPE_BOOK_STATE,
   SET_DISPLAYED_RECIPE,
   NAME_ITEM,
   RESOURCE_PACK_STATUS,
   ADVANCEMENT_TAB,
   SELECT_TRADE,
   SET_BEACON_EFFECT,
   HELD_ITEM_CHANGE,
   UPDATE_COMMAND_BLOCK,
   UPDATE_COMMAND_BLOCK_MINECART,
   CREATIVE_INVENTORY_ACTION,
   UPDATE_JIGSAW_BLOCK,
   UPDATE_STRUCTURE_BLOCK,
   UPDATE_SIGN,
   ANIMATION,
   SPECTATE,
   PLAYER_BLOCK_PLACEMENT,
   USE_ITEM;

   // $FF: synthetic method
   private static u8[] F() {
      return new u8[]{TELEPORT_CONFIRM, QUERY_BLOCK_NBT, SET_DIFFICULTY, CHAT_ACK, CHAT_COMMAND, CHAT_MESSAGE, CHAT_SESSION_UPDATE, CHUNK_BATCH_ACK, CLIENT_STATUS, CLIENT_SETTINGS, TAB_COMPLETE, CONFIGURATION_ACK, CLICK_WINDOW_BUTTON, CLICK_WINDOW, CLOSE_WINDOW, PLUGIN_MESSAGE, EDIT_BOOK, QUERY_ENTITY_NBT, INTERACT_ENTITY, GENERATE_STRUCTURE, KEEP_ALIVE, LOCK_DIFFICULTY, PLAYER_POSITION, PLAYER_POSITION_AND_ROTATION, PLAYER_ROTATION, PLAYER_FLYING, VEHICLE_MOVE, STEER_BOAT, PICK_ITEM, DEBUG_PING, CRAFT_RECIPE_REQUEST, PLAYER_ABILITIES, PLAYER_DIGGING, ENTITY_ACTION, STEER_VEHICLE, PONG, SET_RECIPE_BOOK_STATE, SET_DISPLAYED_RECIPE, NAME_ITEM, RESOURCE_PACK_STATUS, ADVANCEMENT_TAB, SELECT_TRADE, SET_BEACON_EFFECT, HELD_ITEM_CHANGE, UPDATE_COMMAND_BLOCK, UPDATE_COMMAND_BLOCK_MINECART, CREATIVE_INVENTORY_ACTION, UPDATE_JIGSAW_BLOCK, UPDATE_STRUCTURE_BLOCK, UPDATE_SIGN, ANIMATION, SPECTATE, PLAYER_BLOCK_PLACEMENT, USE_ITEM};
   }

   static {
      long var0 = kt.a(4590321505556761903L, 895609525787597516L, MethodHandles.lookup().lookupClass()).a(59131802941314L) ^ 5710034383641L;
      TELEPORT_CONFIRM = new u8("TELEPORT_CONFIRM", 0);
      QUERY_BLOCK_NBT = new u8("QUERY_BLOCK_NBT", 1);
      SET_DIFFICULTY = new u8("SET_DIFFICULTY", 2);
      CHAT_ACK = new u8("CHAT_ACK", 3);
      CHAT_COMMAND = new u8("CHAT_COMMAND", 4);
      CHAT_MESSAGE = new u8("CHAT_MESSAGE", 5);
      CHAT_SESSION_UPDATE = new u8("CHAT_SESSION_UPDATE", 6);
      CHUNK_BATCH_ACK = new u8("CHUNK_BATCH_ACK", 7);
      CLIENT_STATUS = new u8("CLIENT_STATUS", 8);
      CLIENT_SETTINGS = new u8("CLIENT_SETTINGS", 9);
      TAB_COMPLETE = new u8("TAB_COMPLETE", 10);
      CONFIGURATION_ACK = new u8("CONFIGURATION_ACK", 11);
      CLICK_WINDOW_BUTTON = new u8("CLICK_WINDOW_BUTTON", 12);
      CLICK_WINDOW = new u8("CLICK_WINDOW", 13);
      CLOSE_WINDOW = new u8("CLOSE_WINDOW", 14);
      PLUGIN_MESSAGE = new u8("PLUGIN_MESSAGE", 15);
      EDIT_BOOK = new u8("EDIT_BOOK", 16);
      QUERY_ENTITY_NBT = new u8("QUERY_ENTITY_NBT", 17);
      INTERACT_ENTITY = new u8("INTERACT_ENTITY", 18);
      GENERATE_STRUCTURE = new u8("GENERATE_STRUCTURE", 19);
      KEEP_ALIVE = new u8("KEEP_ALIVE", 20);
      LOCK_DIFFICULTY = new u8("LOCK_DIFFICULTY", 21);
      PLAYER_POSITION = new u8("PLAYER_POSITION", 22);
      PLAYER_POSITION_AND_ROTATION = new u8("PLAYER_POSITION_AND_ROTATION", 23);
      PLAYER_ROTATION = new u8("PLAYER_ROTATION", 24);
      PLAYER_FLYING = new u8("PLAYER_FLYING", 25);
      VEHICLE_MOVE = new u8("VEHICLE_MOVE", 26);
      STEER_BOAT = new u8("STEER_BOAT", 27);
      PICK_ITEM = new u8("PICK_ITEM", 28);
      DEBUG_PING = new u8("DEBUG_PING", 29);
      CRAFT_RECIPE_REQUEST = new u8("CRAFT_RECIPE_REQUEST", 30);
      PLAYER_ABILITIES = new u8("PLAYER_ABILITIES", 31);
      PLAYER_DIGGING = new u8("PLAYER_DIGGING", 32);
      ENTITY_ACTION = new u8("ENTITY_ACTION", 33);
      STEER_VEHICLE = new u8("STEER_VEHICLE", 34);
      PONG = new u8("PONG", 35);
      SET_RECIPE_BOOK_STATE = new u8("SET_RECIPE_BOOK_STATE", 36);
      SET_DISPLAYED_RECIPE = new u8("SET_DISPLAYED_RECIPE", 37);
      NAME_ITEM = new u8("NAME_ITEM", 38);
      RESOURCE_PACK_STATUS = new u8("RESOURCE_PACK_STATUS", 39);
      ADVANCEMENT_TAB = new u8("ADVANCEMENT_TAB", 40);
      SELECT_TRADE = new u8("SELECT_TRADE", 41);
      SET_BEACON_EFFECT = new u8("SET_BEACON_EFFECT", 42);
      HELD_ITEM_CHANGE = new u8("HELD_ITEM_CHANGE", 43);
      UPDATE_COMMAND_BLOCK = new u8("UPDATE_COMMAND_BLOCK", 44);
      UPDATE_COMMAND_BLOCK_MINECART = new u8("UPDATE_COMMAND_BLOCK_MINECART", 45);
      CREATIVE_INVENTORY_ACTION = new u8("CREATIVE_INVENTORY_ACTION", 46);
      UPDATE_JIGSAW_BLOCK = new u8("UPDATE_JIGSAW_BLOCK", 47);
      UPDATE_STRUCTURE_BLOCK = new u8("UPDATE_STRUCTURE_BLOCK", 48);
      UPDATE_SIGN = new u8("UPDATE_SIGN", 49);
      ANIMATION = new u8("ANIMATION", 50);
      SPECTATE = new u8("SPECTATE", 51);
      PLAYER_BLOCK_PLACEMENT = new u8("PLAYER_BLOCK_PLACEMENT", 52);
      USE_ITEM = new u8("USE_ITEM", 53);
   }
}
