package com.gmail.olexorus.themis;

import java.lang.invoke.MethodHandles;

public enum vi {
   TELEPORT_CONFIRM,
   QUERY_BLOCK_NBT,
   SELECT_BUNDLE_ITEM,
   SET_DIFFICULTY,
   CHANGE_GAME_MODE,
   CHAT_ACK,
   CHAT_COMMAND_UNSIGNED,
   CHAT_COMMAND,
   CHAT_MESSAGE,
   CHAT_SESSION_UPDATE,
   CHUNK_BATCH_ACK,
   CLIENT_STATUS,
   CLIENT_TICK_END,
   CLIENT_SETTINGS,
   TAB_COMPLETE,
   CONFIGURATION_ACK,
   CLICK_WINDOW_BUTTON,
   CLICK_WINDOW,
   CLOSE_WINDOW,
   SLOT_STATE_CHANGE,
   COOKIE_RESPONSE,
   PLUGIN_MESSAGE,
   DEBUG_SUBSCRIPTION_REQUEST,
   EDIT_BOOK,
   QUERY_ENTITY_NBT,
   INTERACT_ENTITY,
   GENERATE_STRUCTURE,
   KEEP_ALIVE,
   LOCK_DIFFICULTY,
   PLAYER_POSITION,
   PLAYER_POSITION_AND_ROTATION,
   PLAYER_ROTATION,
   PLAYER_FLYING,
   VEHICLE_MOVE,
   STEER_BOAT,
   PICK_ITEM_FROM_BLOCK,
   PICK_ITEM_FROM_ENTITY,
   DEBUG_PING,
   CRAFT_RECIPE_REQUEST,
   PLAYER_ABILITIES,
   PLAYER_DIGGING,
   ENTITY_ACTION,
   PLAYER_INPUT,
   PLAYER_LOADED,
   PONG,
   SET_RECIPE_BOOK_STATE,
   SET_DISPLAYED_RECIPE,
   NAME_ITEM,
   RESOURCE_PACK_STATUS,
   ADVANCEMENT_TAB,
   SELECT_TRADE,
   SET_BEACON_EFFECT,
   HELD_ITEM_CHANGE,
   UPDATE_COMMAND_BLOCK,
   UPDATE_COMMAND_BLOCK_MINECART,
   CREATIVE_INVENTORY_ACTION,
   UPDATE_JIGSAW_BLOCK,
   UPDATE_STRUCTURE_BLOCK,
   SET_TEST_BLOCK,
   UPDATE_SIGN,
   ANIMATION,
   SPECTATE,
   TEST_INSTANCE_BLOCK_ACTION,
   PLAYER_BLOCK_PLACEMENT,
   USE_ITEM,
   CUSTOM_CLICK_ACTION;

   // $FF: synthetic method
   private static vi[] e() {
      return new vi[]{TELEPORT_CONFIRM, QUERY_BLOCK_NBT, SELECT_BUNDLE_ITEM, SET_DIFFICULTY, CHANGE_GAME_MODE, CHAT_ACK, CHAT_COMMAND_UNSIGNED, CHAT_COMMAND, CHAT_MESSAGE, CHAT_SESSION_UPDATE, CHUNK_BATCH_ACK, CLIENT_STATUS, CLIENT_TICK_END, CLIENT_SETTINGS, TAB_COMPLETE, CONFIGURATION_ACK, CLICK_WINDOW_BUTTON, CLICK_WINDOW, CLOSE_WINDOW, SLOT_STATE_CHANGE, COOKIE_RESPONSE, PLUGIN_MESSAGE, DEBUG_SUBSCRIPTION_REQUEST, EDIT_BOOK, QUERY_ENTITY_NBT, INTERACT_ENTITY, GENERATE_STRUCTURE, KEEP_ALIVE, LOCK_DIFFICULTY, PLAYER_POSITION, PLAYER_POSITION_AND_ROTATION, PLAYER_ROTATION, PLAYER_FLYING, VEHICLE_MOVE, STEER_BOAT, PICK_ITEM_FROM_BLOCK, PICK_ITEM_FROM_ENTITY, DEBUG_PING, CRAFT_RECIPE_REQUEST, PLAYER_ABILITIES, PLAYER_DIGGING, ENTITY_ACTION, PLAYER_INPUT, PLAYER_LOADED, PONG, SET_RECIPE_BOOK_STATE, SET_DISPLAYED_RECIPE, NAME_ITEM, RESOURCE_PACK_STATUS, ADVANCEMENT_TAB, SELECT_TRADE, SET_BEACON_EFFECT, HELD_ITEM_CHANGE, UPDATE_COMMAND_BLOCK, UPDATE_COMMAND_BLOCK_MINECART, CREATIVE_INVENTORY_ACTION, UPDATE_JIGSAW_BLOCK, UPDATE_STRUCTURE_BLOCK, SET_TEST_BLOCK, UPDATE_SIGN, ANIMATION, SPECTATE, TEST_INSTANCE_BLOCK_ACTION, PLAYER_BLOCK_PLACEMENT, USE_ITEM, CUSTOM_CLICK_ACTION};
   }

   static {
      long var0 = kt.a(78690224516769283L, 5968094315385198383L, MethodHandles.lookup().lookupClass()).a(65971359240927L) ^ 153703239789L;
      TELEPORT_CONFIRM = new vi("TELEPORT_CONFIRM", 0);
      QUERY_BLOCK_NBT = new vi("QUERY_BLOCK_NBT", 1);
      SELECT_BUNDLE_ITEM = new vi("SELECT_BUNDLE_ITEM", 2);
      SET_DIFFICULTY = new vi("SET_DIFFICULTY", 3);
      CHANGE_GAME_MODE = new vi("CHANGE_GAME_MODE", 4);
      CHAT_ACK = new vi("CHAT_ACK", 5);
      CHAT_COMMAND_UNSIGNED = new vi("CHAT_COMMAND_UNSIGNED", 6);
      CHAT_COMMAND = new vi("CHAT_COMMAND", 7);
      CHAT_MESSAGE = new vi("CHAT_MESSAGE", 8);
      CHAT_SESSION_UPDATE = new vi("CHAT_SESSION_UPDATE", 9);
      CHUNK_BATCH_ACK = new vi("CHUNK_BATCH_ACK", 10);
      CLIENT_STATUS = new vi("CLIENT_STATUS", 11);
      CLIENT_TICK_END = new vi("CLIENT_TICK_END", 12);
      CLIENT_SETTINGS = new vi("CLIENT_SETTINGS", 13);
      TAB_COMPLETE = new vi("TAB_COMPLETE", 14);
      CONFIGURATION_ACK = new vi("CONFIGURATION_ACK", 15);
      CLICK_WINDOW_BUTTON = new vi("CLICK_WINDOW_BUTTON", 16);
      CLICK_WINDOW = new vi("CLICK_WINDOW", 17);
      CLOSE_WINDOW = new vi("CLOSE_WINDOW", 18);
      SLOT_STATE_CHANGE = new vi("SLOT_STATE_CHANGE", 19);
      COOKIE_RESPONSE = new vi("COOKIE_RESPONSE", 20);
      PLUGIN_MESSAGE = new vi("PLUGIN_MESSAGE", 21);
      DEBUG_SUBSCRIPTION_REQUEST = new vi("DEBUG_SUBSCRIPTION_REQUEST", 22);
      EDIT_BOOK = new vi("EDIT_BOOK", 23);
      QUERY_ENTITY_NBT = new vi("QUERY_ENTITY_NBT", 24);
      INTERACT_ENTITY = new vi("INTERACT_ENTITY", 25);
      GENERATE_STRUCTURE = new vi("GENERATE_STRUCTURE", 26);
      KEEP_ALIVE = new vi("KEEP_ALIVE", 27);
      LOCK_DIFFICULTY = new vi("LOCK_DIFFICULTY", 28);
      PLAYER_POSITION = new vi("PLAYER_POSITION", 29);
      PLAYER_POSITION_AND_ROTATION = new vi("PLAYER_POSITION_AND_ROTATION", 30);
      PLAYER_ROTATION = new vi("PLAYER_ROTATION", 31);
      PLAYER_FLYING = new vi("PLAYER_FLYING", 32);
      VEHICLE_MOVE = new vi("VEHICLE_MOVE", 33);
      STEER_BOAT = new vi("STEER_BOAT", 34);
      PICK_ITEM_FROM_BLOCK = new vi("PICK_ITEM_FROM_BLOCK", 35);
      PICK_ITEM_FROM_ENTITY = new vi("PICK_ITEM_FROM_ENTITY", 36);
      DEBUG_PING = new vi("DEBUG_PING", 37);
      CRAFT_RECIPE_REQUEST = new vi("CRAFT_RECIPE_REQUEST", 38);
      PLAYER_ABILITIES = new vi("PLAYER_ABILITIES", 39);
      PLAYER_DIGGING = new vi("PLAYER_DIGGING", 40);
      ENTITY_ACTION = new vi("ENTITY_ACTION", 41);
      PLAYER_INPUT = new vi("PLAYER_INPUT", 42);
      PLAYER_LOADED = new vi("PLAYER_LOADED", 43);
      PONG = new vi("PONG", 44);
      SET_RECIPE_BOOK_STATE = new vi("SET_RECIPE_BOOK_STATE", 45);
      SET_DISPLAYED_RECIPE = new vi("SET_DISPLAYED_RECIPE", 46);
      NAME_ITEM = new vi("NAME_ITEM", 47);
      RESOURCE_PACK_STATUS = new vi("RESOURCE_PACK_STATUS", 48);
      ADVANCEMENT_TAB = new vi("ADVANCEMENT_TAB", 49);
      SELECT_TRADE = new vi("SELECT_TRADE", 50);
      SET_BEACON_EFFECT = new vi("SET_BEACON_EFFECT", 51);
      HELD_ITEM_CHANGE = new vi("HELD_ITEM_CHANGE", 52);
      UPDATE_COMMAND_BLOCK = new vi("UPDATE_COMMAND_BLOCK", 53);
      UPDATE_COMMAND_BLOCK_MINECART = new vi("UPDATE_COMMAND_BLOCK_MINECART", 54);
      CREATIVE_INVENTORY_ACTION = new vi("CREATIVE_INVENTORY_ACTION", 55);
      UPDATE_JIGSAW_BLOCK = new vi("UPDATE_JIGSAW_BLOCK", 56);
      UPDATE_STRUCTURE_BLOCK = new vi("UPDATE_STRUCTURE_BLOCK", 57);
      SET_TEST_BLOCK = new vi("SET_TEST_BLOCK", 58);
      UPDATE_SIGN = new vi("UPDATE_SIGN", 59);
      ANIMATION = new vi("ANIMATION", 60);
      SPECTATE = new vi("SPECTATE", 61);
      TEST_INSTANCE_BLOCK_ACTION = new vi("TEST_INSTANCE_BLOCK_ACTION", 62);
      PLAYER_BLOCK_PLACEMENT = new vi("PLAYER_BLOCK_PLACEMENT", 63);
      USE_ITEM = new vi("USE_ITEM", 64);
      CUSTOM_CLICK_ACTION = new vi("CUSTOM_CLICK_ACTION", 65);
   }
}
