timestamp=1759472440036
git.commit=0fd2a96aca1cec7794e9cc795181d3f4583ee473
git.branch=HEAD
git.org=GrimAnticheat
git.repo=Grim
build.version=2.3.72
build.shade_pe=true
build.relocate=true
build.release=true
