# ModereX Web Panel Version
# Update this file when releasing new panel builds

version=DEV-2026-01-28-003
buildDate=2026-01-28
buildNumber=3
notes=Fix automod rule update disconnect, improved automod tester
