package com.blockforge.moderex.resourcepack;

/**
 * Custom model data constants for ModereX GUI textures.
 * Auto-generated by generate_textures.py
 */
public final class GuiTextures {
    private GuiTextures() {}

    public static final int MODEREX_LOGO = 100000;
    public static final int SHIELD_BLUE = 100001;
    public static final int SHIELD_GREEN = 100002;
    public static final int SHIELD_RED = 100003;
    public static final int SWORD = 100004;
    public static final int GAVEL = 100005;
    public static final int BELL = 100006;
    public static final int SCROLL = 100007;
    public static final int GEAR = 100008;
    public static final int EYE = 100009;
    public static final int CHECKMARK = 100010;
    public static final int X_MARK = 100011;
    public static final int WARNING = 100012;
    public static final int LIGHTNING = 100013;
    public static final int USER = 100014;
    public static final int STAFF = 100015;
    public static final int COMBAT = 100016;
    public static final int MOVEMENT = 100017;
    public static final int PACKET = 100018;
    public static final int WORLD = 100019;
    public static final int MISC = 100020;
    public static final int ARROW_RIGHT = 100021;
    public static final int ARROW_LEFT = 100022;
    public static final int PRESET = 100023;
}
